import { HomeProfile } from '@/types';

export const DEFAULT_PROFILE: HomeProfile = {
  id: 'default',
  nickname: '',
  address: '',
  city: '',
  state: '',
  zipCode: '',
  homeType: 'single-family',
  yearBuilt: '',
  squareFootage: '',
  lotSize: '',
  bedrooms: '',
  bathrooms: '',
  stories: '1',
  foundationType: 'slab',
  roofType: 'asphalt-shingle',
  roofAge: '',
  heatingCoolingType: 'central-ac',
  waterHeaterType: 'tank-gas',
  garageType: 'none',
  hasPool: false,
  hasHoa: false,
  hoaAmount: '',
  purchaseDate: '',
  notes: '',
  zillowLink: '',
  householdMembers: [],
};
