import { HomeProfile } from '@/types';

export const DEFAULT_PROFILE: HomeProfile = {
  id: 'default',
  nickname: '',
  address: '',
  city: '',
  state: '',
  zipCode: '',
  homeType: 'single-family',
  yearBuilt: null,
  squareFootage: null,
  lotSize: null,
  bedrooms: null,
  bathrooms: null,
  stories: 1,
  foundationType: 'slab',
  roofType: 'asphalt-shingle',
  roofAge: null,
  heatingCoolingType: 'central-ac',
  waterHeaterType: 'tank-gas',
  garageType: 'none',
  hasPool: false,
  hasHoa: false,
  hoaAmount: null,
  purchaseDate: '',
  notes: '',
  zillowLink: '',
  householdMembers: [],
};
