import { StyleSheet } from 'react-native';
import { ColorScheme } from '@/constants/colors';

const createStyles = (c: ColorScheme) => StyleSheet.create({
  container: { flex: 1, backgroundColor: c.background },
  toolbarRow: { flexDirection: 'row', alignItems: 'center' },
  filterScroll: { flexGrow: 0, flex: 1 },
  filterRow: { paddingHorizontal: 20, paddingVertical: 10, gap: 8 },
  filterChip: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, backgroundColor: c.surface, borderWidth: 1, borderColor: c.border },
  filterChipActive: { backgroundColor: c.primary, borderColor: c.primary },
  filterText: { fontSize: 13, fontWeight: '600', color: c.textSecondary, lineHeight: 17 },
  filterTextActive: { color: c.white },
  filterBadge: { backgroundColor: c.surfaceAlt, borderRadius: 10, paddingHorizontal: 6, paddingVertical: 1, minWidth: 20, alignItems: 'center' },
  filterBadgeActive: { backgroundColor: 'rgba(255,255,255,0.25)' },
  filterBadgeText: { fontSize: 11, fontWeight: '600', color: c.textSecondary, lineHeight: 15 },
  filterBadgeTextActive: { color: c.white },
  sortPillRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 20, paddingBottom: 12 },
  sortPill: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, backgroundColor: c.surface, borderWidth: 1, borderColor: c.border },
  sortPillActive: { backgroundColor: c.primary, borderColor: c.primary },
  sortPillText: { fontSize: 13, fontWeight: '600', color: c.textSecondary, lineHeight: 17 },
  sortPillTextActive: { color: c.white },
  list: { paddingHorizontal: 20, paddingTop: 4 },
  groupContainer: { marginBottom: 16 },
  groupHeader: { flexDirection: 'row', alignItems: 'center', backgroundColor: c.surface, borderRadius: 12, paddingVertical: 12, paddingHorizontal: 14, marginBottom: 8, shadowColor: c.cardShadow, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 1, shadowRadius: 4, elevation: 1 },
  groupAccentBar: { width: 4, height: 28, borderRadius: 2, marginRight: 12 },
  groupHeaderContent: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8 },
  groupTitle: { fontSize: 15, fontWeight: '700', color: c.text, lineHeight: 20 },
  groupCountBadge: { borderRadius: 10, paddingHorizontal: 8, paddingVertical: 2, minWidth: 24, alignItems: 'center' },
  groupCountText: { fontSize: 12, fontWeight: '700', lineHeight: 16 },
  groupChevronWrap: { width: 28, height: 28, borderRadius: 14, justifyContent: 'center', alignItems: 'center' },
  groupContent: { paddingLeft: 4 },
  taskCard: { flexDirection: 'row', backgroundColor: c.surface, borderRadius: 16, padding: 16, marginBottom: 10, borderLeftWidth: 3, borderLeftColor: 'transparent', shadowColor: c.cardShadow, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 1, shadowRadius: 8, elevation: 1 },
  taskCardOverdue: { borderLeftColor: c.danger },
  taskCardCompleted: { backgroundColor: c.successLight },
  taskCardArchived: { backgroundColor: c.surfaceAlt, opacity: 0.8 },
  taskLeft: { marginRight: 14, paddingTop: 2 },
  checkCircle: { width: 28, height: 28, borderRadius: 14, borderWidth: 2, borderColor: c.border, justifyContent: 'center', alignItems: 'center' },
  checkCircleOverdue: { borderColor: c.danger },
  checkCircleDone: { width: 28, height: 28, borderRadius: 14, backgroundColor: c.success, justifyContent: 'center', alignItems: 'center' },
  checkCircleArchived: { width: 28, height: 28, borderRadius: 14, backgroundColor: c.border, justifyContent: 'center', alignItems: 'center' },
  taskBody: { flex: 1 },
  taskTitle: { fontSize: 15, fontWeight: '600', color: c.text, marginBottom: 3, lineHeight: 20 },
  taskTitleDone: { textDecorationLine: 'line-through', color: c.textSecondary },
  taskTitleArchived: { color: c.textTertiary },
  taskDesc: { fontSize: 12, color: c.textTertiary, marginBottom: 8, lineHeight: 16 },
  taskFooter: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 6 },
  taskDateRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  taskDateText: { fontSize: 12, color: c.textSecondary, lineHeight: 16 },
  footerDot: { width: 3, height: 3, borderRadius: 1.5, backgroundColor: c.textTertiary },
  taskApplianceName: { fontSize: 11, color: c.textTertiary, lineHeight: 15, flexShrink: 1, maxWidth: '40%' },
  recurringBadge: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: c.primaryLight, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
  recurringText: { fontSize: 10, fontWeight: '500', color: c.primary, lineHeight: 14 },
  taskRight: { alignItems: 'flex-end', justifyContent: 'flex-start', gap: 6, marginLeft: 8 },
  priorityTag: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  priorityText: { fontSize: 10, fontWeight: '700', textTransform: 'capitalize' as const, lineHeight: 14 },
  emptyState: { alignItems: 'center', paddingVertical: 60, gap: 8 },
  emptyIconWrap: { width: 64, height: 64, borderRadius: 32, backgroundColor: c.primaryLight, justifyContent: 'center', alignItems: 'center', marginBottom: 4 },
  emptyTitle: { fontSize: 20, fontWeight: '700', color: c.text, lineHeight: 26 },
  emptySubtitle: { fontSize: 15, color: c.textSecondary, textAlign: 'center', lineHeight: 21, paddingHorizontal: 20 },
  completedSection: { marginTop: 8 },
  completedDivider: { height: 1, backgroundColor: c.border, marginBottom: 14, marginHorizontal: 4 },
  completedHeader: { flexDirection: 'row', alignItems: 'center', backgroundColor: c.successLight, borderRadius: 12, paddingVertical: 12, paddingHorizontal: 14, marginBottom: 8 },
  completedHeaderLeft: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 10 },
  completedIconWrap: { width: 30, height: 30, borderRadius: 15, backgroundColor: c.success + '18', justifyContent: 'center', alignItems: 'center' },
  completedHeaderTitle: { fontSize: 15, fontWeight: '700', color: c.success, lineHeight: 20 },
  completedCountBadge: { backgroundColor: c.success + '18', borderRadius: 10, paddingHorizontal: 8, paddingVertical: 2, minWidth: 24, alignItems: 'center' },
  completedCountText: { fontSize: 12, fontWeight: '700', color: c.success, lineHeight: 16 },
  completedChevronWrap: { width: 28, height: 28, borderRadius: 14, backgroundColor: c.success + '12', justifyContent: 'center', alignItems: 'center' },
  completedContent: { paddingLeft: 4 },
  exportSection: { marginTop: 16, marginBottom: 8 },
  exportHeader: { flexDirection: 'row', alignItems: 'center', backgroundColor: c.surface, borderRadius: 16, paddingVertical: 14, paddingHorizontal: 16, shadowColor: c.cardShadow, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 1, shadowRadius: 8, elevation: 1 },
  exportHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  exportHeaderIcon: { width: 40, height: 40, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  exportHeaderTitle: { fontSize: 16, fontWeight: '700', color: c.text, lineHeight: 21 },
  exportHeaderSubtitle: { fontSize: 12, color: c.textTertiary, lineHeight: 16, marginTop: 1 },
  exportGrid: { marginTop: 12, flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  exportGridItem: { width: '48%' as any, backgroundColor: c.surface, borderRadius: 14, paddingVertical: 18, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center', shadowColor: c.cardShadow, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 1, shadowRadius: 4, elevation: 1 },
  exportGridIcon: { width: 48, height: 48, borderRadius: 14, justifyContent: 'center', alignItems: 'center', marginBottom: 10 },
  exportGridTitle: { fontSize: 14, fontWeight: '600', color: c.text, lineHeight: 18, textAlign: 'center' as const },
  exportGridDesc: { fontSize: 11, color: c.textTertiary, lineHeight: 15, marginTop: 2, textAlign: 'center' as const },
});

export default createStyles;
