import { StyleSheet } from 'react-native';
import Colors from '@/constants/colors';

export const formStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  scanOptions: {
    gap: 10,
    marginBottom: 24,
  },
  scanCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.primaryLight,
    borderRadius: 16,
    padding: 16,
    gap: 12,
    borderWidth: 1.5,
    borderColor: Colors.primary + '25',
    borderStyle: 'dashed',
  },
  scanCardLabel: {
    backgroundColor: Colors.accentLight,
    borderColor: Colors.accent + '25',
  },
  scanCardActive: {
    borderColor: Colors.primary + '60',
    backgroundColor: Colors.primaryLight,
  },
  scanIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scanIconWrapLabel: {
    backgroundColor: Colors.white,
  },
  scanTextWrap: {
    flex: 1,
  },
  scanTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  scanTitle: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: Colors.primaryDark,
    lineHeight: 19,
  },
  scanTitleLabel: {
    color: Colors.accentDark,
  },
  scanSubtitle: {
    fontSize: 12,
    color: Colors.primary,
    marginTop: 1,
    opacity: 0.8,
    lineHeight: 16,
  },
  scanSubtitleLabel: {
    color: Colors.accent,
  },
  imagePreviewCard: {
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 24,
    backgroundColor: Colors.surface,
    shadowColor: Colors.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 2,
  },
  previewImage: {
    width: '100%',
    height: 200,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  imageOverlay: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
  removeImageBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  analyzingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
  },
  analyzingText: {
    color: Colors.white,
    fontSize: 13,
    fontWeight: '600' as const,
    lineHeight: 17,
  },
  rescanRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rescanBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  rescanDivider: {
    width: 1,
    height: 16,
    backgroundColor: Colors.borderLight,
  },
  rescanText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: Colors.primary,
    lineHeight: 19,
  },
  section: {
    marginBottom: 20,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: Colors.textSecondary,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.8,
    marginBottom: 8,
    marginLeft: 4,
    lineHeight: 17,
  },
  card: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: Colors.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 1,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  inputContent: {
    flex: 1,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: Colors.textSecondary,
    marginBottom: 4,
    lineHeight: 16,
  },
  textInput: {
    fontSize: 16,
    fontWeight: '500' as const,
    color: Colors.text,
    padding: 0,
    margin: 0,
    lineHeight: 22,
  },
  divider: {
    height: 1,
    backgroundColor: Colors.borderLight,
    marginLeft: 16,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  categoryChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 22,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  categoryChipActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  categoryChipText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: Colors.textSecondary,
    lineHeight: 17,
  },
  categoryChipTextActive: {
    color: Colors.white,
  },
  notesRow: {
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  notesInput: {
    fontSize: 15,
    fontWeight: '400' as const,
    color: Colors.text,
    minHeight: 80,
    padding: 0,
    margin: 0,
    lineHeight: 21,
  },
  receiptScanCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.warningLight,
    borderRadius: 16,
    padding: 16,
    gap: 12,
    borderWidth: 1.5,
    borderColor: Colors.warning + '25',
    borderStyle: 'dashed' as const,
    marginBottom: 4,
  },
  receiptScanCardActive: {
    borderColor: Colors.warning + '60',
  },
  receiptScanIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  receiptScanTitle: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#8B6914',
    lineHeight: 19,
  },
  receiptScanSubtitle: {
    fontSize: 12,
    color: Colors.warning,
    marginTop: 1,
    opacity: 0.9,
    lineHeight: 16,
  },
  receiptPreviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: 10,
    marginTop: 8,
  },
  receiptThumbnail: {
    width: 48,
    height: 48,
    borderRadius: 8,
  },
  receiptPreviewInfo: {
    flex: 1,
    gap: 2,
  },
  receiptPreviewLabel: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: Colors.text,
  },
  receiptRemoveText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: Colors.danger,
  },
  photosSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 0,
  },
  addPhotoSmallBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: Colors.primaryLight,
    marginBottom: 8,
  },
  addPhotoSmallText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: Colors.primary,
  },
  photosRow: {
    gap: 10,
    paddingBottom: 4,
  },
  photoThumbWrap: {
    alignItems: 'center',
    gap: 4,
  },
  photoThumb: {
    width: 80,
    height: 80,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: Colors.border,
    position: 'relative' as const,
  },
  photoThumbPrimary: {
    borderColor: Colors.primary,
    borderWidth: 2.5,
  },
  photoThumbImage: {
    width: '100%',
    height: '100%',
  },
  primaryBadge: {
    position: 'absolute' as const,
    bottom: 4,
    left: 4,
    backgroundColor: Colors.primary,
    borderRadius: 8,
    width: 18,
    height: 18,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  photoRemoveBtn: {
    position: 'absolute' as const,
    top: 3,
    right: 3,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 8,
    width: 16,
    height: 16,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  photoThumbLabel: {
    fontSize: 9,
    fontWeight: '500' as const,
    color: Colors.textTertiary,
    textAlign: 'center' as const,
  },
  addPhotoThumb: {
    width: 80,
    height: 80,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderStyle: 'dashed' as const,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    backgroundColor: Colors.surfaceAlt,
  },
  saveBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center' as const,
    marginTop: 4,
  },
  saveBtnDisabled: {
    opacity: 0.5,
  },
  saveBtnText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: Colors.white,
    lineHeight: 22,
  },
  notFound: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    backgroundColor: Colors.background,
  },
  notFoundText: {
    fontSize: 18,
    fontWeight: '600' as const,
    color: Colors.textSecondary,
    marginBottom: 16,
  },
  backBtn: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: Colors.primary,
  },
  backBtnText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: Colors.white,
  },
});
