import { StyleSheet } from 'react-native';
import { ColorScheme } from '@/constants/colors';

const createStyles = (c: ColorScheme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: c.background,
  },
  content: {
    paddingHorizontal: 20,
  },
  heroCard: {
    backgroundColor: c.surface,
    borderRadius: 20,
    padding: 22,
    marginBottom: 24,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 16,
    elevation: 3,
  },
  heroTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  heroStatBlock: {
    flex: 1,
    alignItems: 'center',
    gap: 6,
  },
  heroStatIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 2,
  },
  heroLabel: {
    fontSize: 13,
    color: c.textSecondary,
    lineHeight: 17,
  },
  heroAmount: {
    fontSize: 28,
    fontWeight: '800' as const,
    letterSpacing: -0.8,
    lineHeight: 34,
  },
  heroDivider: {
    width: 1,
    height: 60,
    backgroundColor: c.borderLight,
  },
  heroStats: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: c.borderLight,
    paddingTop: 18,
  },
  heroStat: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  heroStatIcon: {
    width: 30,
    height: 30,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 2,
  },
  heroStatLabel: {
    fontSize: 11,
    color: c.textTertiary,
    lineHeight: 15,
  },
  heroStatValue: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: c.text,
    lineHeight: 20,
  },
  heroStatDivider: {
    width: 1,
    height: 40,
    backgroundColor: c.borderLight,
  },
  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700' as const,
    color: c.text,
    marginBottom: 12,
    letterSpacing: -0.3,
    lineHeight: 26,
  },
  seeAllBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    marginBottom: 12,
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: c.primary,
  },
  prosRow: {
    gap: 12,
    paddingBottom: 4,
  },
  proCard: {
    width: 140,
    backgroundColor: c.surface,
    borderRadius: 16,
    padding: 14,
    alignItems: 'center',
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 1,
  },
  proAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#4A7FBF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  proAvatarText: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: '#FFFFFF',
  },
  proName: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: c.text,
    textAlign: 'center',
    marginBottom: 2,
    lineHeight: 17,
  },
  proSpecialty: {
    fontSize: 11,
    color: c.textTertiary,
    textAlign: 'center',
    marginBottom: 6,
    lineHeight: 15,
  },
  proPhoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 6,
  },
  proPhone: {
    fontSize: 10,
    color: c.textTertiary,
    lineHeight: 14,
  },
  proExpenseBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: c.primaryLight,
    borderRadius: 8,
  },
  proExpenseCount: {
    fontSize: 10,
    fontWeight: '600' as const,
    color: c.primary,
    lineHeight: 14,
  },
  categoryCard: {
    backgroundColor: c.surface,
    borderRadius: 16,
    padding: 16,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 1,
  },
  categoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    gap: 12,
  },
  categoryRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: c.borderLight,
  },
  categoryDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  categoryInfo: {
    flex: 1,
  },
  categoryLabel: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: c.text,
    marginBottom: 4,
    lineHeight: 17,
  },
  categoryBarContainer: {
    height: 5,
    backgroundColor: c.surfaceAlt,
    borderRadius: 2.5,
    overflow: 'hidden',
  },
  categoryBar: {
    height: '100%',
    borderRadius: 2.5,
  },
  categoryAmount: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: c.text,
    minWidth: 56,
    textAlign: 'right',
  },
  expenseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.surface,
    borderRadius: 14,
    padding: 14,
    marginBottom: 8,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 1,
  },
  expenseDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 12,
  },
  expenseInfo: {
    flex: 1,
  },
  expenseDesc: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: c.text,
    marginBottom: 2,
    lineHeight: 20,
  },
  expenseMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  expenseCategory: {
    fontSize: 12,
    color: c.textTertiary,
    lineHeight: 16,
  },
  expenseBadges: {
    flexDirection: 'row',
    gap: 4,
  },
  expenseBadge: {
    width: 20,
    height: 20,
    borderRadius: 6,
    backgroundColor: c.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  expenseProvider: {
    fontSize: 11,
    fontWeight: '500' as const,
    color: c.primary,
    marginTop: 2,
    lineHeight: 15,
  },
  expenseRight: {
    alignItems: 'flex-end',
    marginLeft: 8,
  },
  expenseAmount: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: c.danger,
  },
  expensePayment: {
    fontSize: 10,
    color: c.textTertiary,
    marginTop: 2,
    lineHeight: 14,
  },
  emptyState: {
    backgroundColor: c.surface,
    borderRadius: 16,
    padding: 28,
    alignItems: 'center',
  },
  emptyIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: c.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: c.text,
    marginBottom: 4,
    lineHeight: 22,
  },
  emptySubtext: {
    fontSize: 14,
    color: c.textTertiary,
    lineHeight: 19,
  },
  exportHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: c.surface,
    borderRadius: 16,
    padding: 16,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 1,
  },
  exportHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  exportHeaderIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  exportHeaderTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: c.text,
    lineHeight: 21,
  },
  exportHeaderSubtitle: {
    fontSize: 12,
    color: c.textTertiary,
    lineHeight: 16,
    marginTop: 1,
  },
  exportGrid: {
    marginTop: 12,
    gap: 10,
  },
  exportGridRow: {
    flexDirection: 'row',
    gap: 10,
  },
  exportGridItem: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: c.surface,
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 8,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 1,
  },
  exportGridIcon: {
    width: 52,
    height: 52,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  exportAppBadge: {
    width: 40,
    height: 40,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  exportAppLetter: {
    fontSize: 20,
    fontWeight: '800' as const,
    color: '#FFFFFF',
    letterSpacing: -0.5,
  },
  exportGridLabel: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: c.text,
    lineHeight: 17,
  },
  sheetsIconGrid: {
    width: 18,
    height: 18,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 2,
  },
  sheetsCell: {
    width: 8,
    height: 8,
    borderRadius: 1.5,
  },
  numbersBarGroup: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 3,
    height: 16,
  },
  numbersBar: {
    width: 5,
    borderRadius: 1.5,
  },
});

export default createStyles;
