import { StyleSheet } from 'react-native';
import { ColorScheme } from '@/constants/colors';
import { Radius, Spacing, cardShadowSubtle, cardShadowSm, cardShadowLg } from '@/constants/layout';

const createStyles = (c: ColorScheme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: c.background,
  },
  content: {
    paddingHorizontal: Spacing.xl,
  },
  heroCard: {
    backgroundColor: c.surface,
    borderRadius: Radius.cardXl,
    padding: 22,
    marginBottom: Spacing.xxl,
    ...cardShadowLg(c),
  },
  heroTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.xl,
  },
  heroStatBlock: {
    flex: 1,
    alignItems: 'center',
    gap: Spacing.xs,
  },
  heroStatIconWrap: {
    width: 36,
    height: 36,
    borderRadius: Radius.lg,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 2,
  },
  heroLabel: {
    fontSize: 13,
    color: c.textSecondary,
    lineHeight: 17,
  },
  heroAmount: {
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.8,
    lineHeight: 34,
  },
  heroDivider: {
    width: 1,
    height: 60,
    backgroundColor: c.borderLight,
  },
  heroStats: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: c.borderLight,
    paddingTop: 18,
  },
  heroStat: {
    flex: 1,
    alignItems: 'center',
    gap: Spacing.xs,
  },
  heroStatIcon: {
    width: 30,
    height: 30,
    borderRadius: Radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 2,
  },
  heroStatLabel: {
    fontSize: 11,
    color: c.textTertiary,
    lineHeight: 15,
  },
  heroStatValue: {
    fontSize: 15,
    fontWeight: '700',
    color: c.text,
    lineHeight: 20,
  },
  heroStatDivider: {
    width: 1,
    height: 40,
    backgroundColor: c.borderLight,
  },
  section: {
    marginBottom: Spacing.xxl,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: c.text,
    marginBottom: Spacing.md,
    letterSpacing: -0.3,
    lineHeight: 26,
  },
  seeAllBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    marginBottom: Spacing.md,
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: '600',
    color: c.primary,
  },
  prosRow: {
    gap: Spacing.md,
    paddingBottom: Spacing.xs,
  },
  proCard: {
    width: 140,
    backgroundColor: c.surface,
    borderRadius: Radius.card,
    padding: Spacing.xl,
    alignItems: 'center',
    ...cardShadowSm(c),
  },
  proAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#4A7FBF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Spacing.sm,
  },
  proAvatarText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  proName: {
    fontSize: 13,
    fontWeight: '700',
    color: c.text,
    textAlign: 'center',
    marginBottom: 2,
    lineHeight: 17,
  },
  proSpecialty: {
    fontSize: 11,
    color: c.textTertiary,
    textAlign: 'center',
    marginBottom: Spacing.xs,
    lineHeight: 15,
  },
  proPhoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    marginBottom: Spacing.xs,
  },
  proPhone: {
    fontSize: 10,
    color: c.textTertiary,
    lineHeight: 14,
  },
  proExpenseBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    backgroundColor: c.primaryLight,
    borderRadius: Radius.sm,
  },
  proExpenseCount: {
    fontSize: 10,
    fontWeight: '600',
    color: c.primary,
    lineHeight: 14,
  },
  categoryCard: {
    backgroundColor: c.surface,
    borderRadius: Radius.card,
    padding: Spacing.lg,
    ...cardShadowSm(c),
  },
  categoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing.md,
    gap: Spacing.md,
  },
  categoryRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: c.borderLight,
  },
  categoryDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  categoryInfo: {
    flex: 1,
  },
  categoryLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: c.text,
    marginBottom: Spacing.xs,
    lineHeight: 17,
  },
  categoryBarContainer: {
    height: 5,
    backgroundColor: c.surfaceAlt,
    borderRadius: 2.5,
    overflow: 'hidden',
  },
  categoryBar: {
    height: '100%',
    borderRadius: 2.5,
  },
  categoryAmount: {
    fontSize: 14,
    fontWeight: '700',
    color: c.text,
    minWidth: 56,
    textAlign: 'right',
  },
  expenseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.surface,
    borderRadius: Radius.xl,
    padding: Spacing.xl,
    marginBottom: Spacing.sm,
    ...cardShadowSubtle(c),
  },
  expenseDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: Spacing.md,
  },
  expenseInfo: {
    flex: 1,
  },
  expenseDesc: {
    fontSize: 15,
    fontWeight: '600',
    color: c.text,
    marginBottom: 2,
    lineHeight: 20,
  },
  expenseMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  expenseCategory: {
    fontSize: 12,
    color: c.textTertiary,
    lineHeight: 16,
  },
  expenseBadges: {
    flexDirection: 'row',
    gap: Spacing.xs,
  },
  expenseBadge: {
    width: 20,
    height: 20,
    borderRadius: Radius.xs,
    backgroundColor: c.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  expenseProvider: {
    fontSize: 11,
    fontWeight: '500',
    color: c.primary,
    marginTop: 2,
    lineHeight: 15,
  },
  expenseRight: {
    alignItems: 'flex-end',
    marginLeft: Spacing.sm,
  },
  expenseAmount: {
    fontSize: 15,
    fontWeight: '700',
    color: c.danger,
  },
  expensePayment: {
    fontSize: 10,
    color: c.textTertiary,
    marginTop: 2,
    lineHeight: 14,
  },
  emptyState: {
    backgroundColor: c.surface,
    borderRadius: Radius.card,
    padding: Spacing.xxxl,
    alignItems: 'center',
  },
  emptyIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: c.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: '600',
    color: c.text,
    marginBottom: Spacing.xs,
    lineHeight: 22,
  },
  emptySubtext: {
    fontSize: 14,
    color: c.textTertiary,
    lineHeight: 19,
  },
  exportHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: c.surface,
    borderRadius: Radius.card,
    padding: Spacing.lg,
    ...cardShadowSm(c),
  },
  exportHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    flex: 1,
  },
  exportHeaderIcon: {
    width: 40,
    height: 40,
    borderRadius: Radius.lg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  exportHeaderTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: c.text,
    lineHeight: 21,
  },
  exportHeaderSubtitle: {
    fontSize: 12,
    color: c.textTertiary,
    lineHeight: 16,
    marginTop: 1,
  },
  exportGrid: {
    marginTop: Spacing.md,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.md,
  },
  exportGridItem: {
    width: '48%' as any,
    backgroundColor: c.surface,
    borderRadius: Radius.xl,
    paddingVertical: Radius.cardLg,
    paddingHorizontal: Spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    ...cardShadowSubtle(c),
  },
  exportGridIcon: {
    width: 48,
    height: 48,
    borderRadius: Radius.xl,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  exportGridTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: c.text,
    lineHeight: 18,
    textAlign: 'center' as const,
  },
  exportGridDesc: {
    fontSize: 11,
    color: c.textTertiary,
    lineHeight: 15,
    marginTop: 2,
    textAlign: 'center' as const,
  },
});

export default createStyles;
