import { StyleSheet } from 'react-native';
import Colors from '@/constants/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    paddingHorizontal: 20,
  },
  heroCard: {
    backgroundColor: Colors.surface,
    borderRadius: 20,
    padding: 22,
    marginBottom: 24,
    shadowColor: Colors.cardShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 16,
    elevation: 3,
  },
  heroTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 18,
  },
  heroLabel: {
    fontSize: 14,
    color: Colors.textSecondary,
    marginBottom: 4,
    lineHeight: 19,
  },
  heroAmount: {
    fontSize: 34,
    fontWeight: '800' as const,
    letterSpacing: -1,
    lineHeight: 40,
  },
  heroPercentBadge: {
    alignItems: 'center',
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  heroPercentText: {
    fontSize: 20,
    fontWeight: '700' as const,
    lineHeight: 24,
  },
  heroPercentSub: {
    fontSize: 10,
    color: Colors.textTertiary,
    lineHeight: 14,
  },
  progressContainer: {
    marginBottom: 20,
  },
  progressBg: {
    height: 6,
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 3,
  },
  progressLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  progressSpent: {
    fontSize: 12,
    color: Colors.textSecondary,
    lineHeight: 16,
  },
  progressTotal: {
    fontSize: 12,
    color: Colors.textTertiary,
    lineHeight: 16,
  },
  budgetEditBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  heroStats: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: Colors.borderLight,
    paddingTop: 18,
  },
  heroStat: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  heroStatIcon: {
    width: 30,
    height: 30,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 2,
  },
  heroStatLabel: {
    fontSize: 11,
    color: Colors.textTertiary,
    lineHeight: 15,
  },
  heroStatValue: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: Colors.text,
    lineHeight: 20,
  },
  heroDivider: {
    width: 1,
    height: 40,
    backgroundColor: Colors.borderLight,
  },
  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700' as const,
    color: Colors.text,
    marginBottom: 12,
    letterSpacing: -0.3,
    lineHeight: 26,
  },
  seeAllBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    marginBottom: 12,
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: Colors.primary,
  },
  prosRow: {
    gap: 12,
    paddingBottom: 4,
  },
  proCard: {
    width: 140,
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 14,
    alignItems: 'center',
    shadowColor: Colors.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 1,
  },
  proAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#4A7FBF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  proAvatarText: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: Colors.white,
  },
  proName: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: Colors.text,
    textAlign: 'center',
    marginBottom: 2,
    lineHeight: 17,
  },
  proSpecialty: {
    fontSize: 11,
    color: Colors.textTertiary,
    textAlign: 'center',
    marginBottom: 6,
    lineHeight: 15,
  },
  proPhoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 6,
  },
  proPhone: {
    fontSize: 10,
    color: Colors.textTertiary,
    lineHeight: 14,
  },
  proExpenseBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: Colors.primaryLight,
    borderRadius: 8,
  },
  proExpenseCount: {
    fontSize: 10,
    fontWeight: '600' as const,
    color: Colors.primary,
    lineHeight: 14,
  },
  categoryCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 16,
    shadowColor: Colors.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 1,
  },
  categoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    gap: 12,
  },
  categoryRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  categoryDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  categoryInfo: {
    flex: 1,
  },
  categoryLabel: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: Colors.text,
    marginBottom: 4,
    lineHeight: 17,
  },
  categoryBarContainer: {
    height: 5,
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 2.5,
    overflow: 'hidden',
  },
  categoryBar: {
    height: '100%',
    borderRadius: 2.5,
  },
  categoryAmount: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: Colors.text,
    minWidth: 56,
    textAlign: 'right',
  },
  expenseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 14,
    marginBottom: 8,
    shadowColor: Colors.cardShadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 1,
  },
  expenseDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 12,
  },
  expenseInfo: {
    flex: 1,
  },
  expenseDesc: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: Colors.text,
    marginBottom: 2,
    lineHeight: 20,
  },
  expenseMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  expenseCategory: {
    fontSize: 12,
    color: Colors.textTertiary,
    lineHeight: 16,
  },
  expenseBadges: {
    flexDirection: 'row',
    gap: 4,
  },
  expenseBadge: {
    width: 20,
    height: 20,
    borderRadius: 6,
    backgroundColor: Colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  expenseProvider: {
    fontSize: 11,
    fontWeight: '500' as const,
    color: '#4A7FBF',
    marginTop: 2,
    lineHeight: 15,
  },
  expenseRight: {
    alignItems: 'flex-end',
    marginLeft: 8,
  },
  expenseAmount: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: Colors.danger,
  },
  expensePayment: {
    fontSize: 10,
    color: Colors.textTertiary,
    marginTop: 2,
    lineHeight: 14,
  },
  emptyState: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 28,
    alignItems: 'center',
  },
  emptyIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: Colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: Colors.text,
    marginBottom: 4,
    lineHeight: 22,
  },
  emptySubtext: {
    fontSize: 14,
    color: Colors.textTertiary,
    lineHeight: 19,
  },
});
