import { StyleSheet } from 'react-native';
import { ColorScheme } from '@/constants/colors';
import { Radius, Spacing, cardShadowSm, cardShadowMd } from '@/constants/layout';

const createStyles = (c: ColorScheme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: c.background,
  },
  content: {
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.md,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: c.background,
  },
  loadingText: {
    fontSize: 16,
    lineHeight: 22,
    color: c.textSecondary,
  },
  greetingSection: {
    marginBottom: Spacing.xl,
  },
  greeting: {
    fontSize: 30,
    fontWeight: '800',
    color: c.text,
    letterSpacing: -0.8,
    lineHeight: 36,
  },
  greetingSubtitle: {
    fontSize: 15,
    lineHeight: 21,
    color: c.textSecondary,
    marginTop: Spacing.xs,
  },
  alertBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.dangerLight,
    borderRadius: Radius.xl,
    padding: Spacing.xl,
    marginBottom: Spacing.lg,
    gap: Spacing.md,
  },
  alertIconWrap: {
    width: 36,
    height: 36,
    borderRadius: Radius.md,
    backgroundColor: c.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  alertContent: {
    flex: 1,
  },
  alertTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: c.danger,
    lineHeight: 19,
  },
  alertSubtitle: {
    fontSize: 12,
    color: c.danger,
    opacity: 0.7,
    marginTop: 1,
    lineHeight: 16,
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: Radius.cardLg,
    marginHorizontal: -4,
  },
  quickAction: {
    width: '50%',
    paddingHorizontal: Spacing.xs,
    paddingVertical: Spacing.xs,
  },
  quickActionInner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.surface,
    borderRadius: Radius.xl,
    paddingVertical: Spacing.xl,
    paddingHorizontal: Spacing.xl,
    gap: Spacing.md,
    ...cardShadowSm(c),
    flex: 1,
  },
  quickActionIcon: {
    width: 36,
    height: 36,
    borderRadius: Radius.md,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quickActionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: c.text,
    lineHeight: 17,
  },
  budgetCard: {
    backgroundColor: c.surface,
    borderRadius: Radius.cardLg,
    padding: Radius.cardLg,
    marginBottom: Spacing.xxl,
    ...cardShadowMd(c),
  },
  budgetLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: c.textSecondary,
    lineHeight: 19,
    marginBottom: Spacing.xl,
  },
  spendingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  spendingItem: {
    flex: 1,
    alignItems: 'center',
  },
  spendingAmountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  spendingAmount: {
    fontSize: 22,
    fontWeight: '700',
    color: c.text,
    letterSpacing: -0.3,
    lineHeight: 28,
    flexShrink: 1,
  },
  spendingPeriod: {
    fontSize: 12,
    color: c.textTertiary,
    marginTop: 2,
    lineHeight: 16,
  },
  spendingDivider: {
    width: 1,
    height: 36,
    backgroundColor: c.border,
    marginHorizontal: Spacing.md,
  },
  section: {
    marginBottom: Spacing.xxl,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: c.text,
    letterSpacing: -0.3,
    lineHeight: 26,
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: '600',
    color: c.primary,
    lineHeight: 19,
  },
  taskCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.surface,
    borderRadius: Radius.xl,
    padding: Spacing.lg,
    marginBottom: Spacing.sm,
    ...cardShadowSm(c),
  },
  priorityIndicator: {
    width: 4,
    height: 32,
    borderRadius: 2,
    marginEnd: Spacing.xl,
  },
  taskContent: {
    flex: 1,
  },
  taskTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: c.text,
    marginBottom: Spacing.xs,
    lineHeight: 20,
  },
  taskMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  metaDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: c.textTertiary,
  },
  taskDate: {
    fontSize: 12,
    color: c.textSecondary,
    lineHeight: 16,
  },
  taskAppliance: {
    fontSize: 12,
    color: c.textTertiary,
    lineHeight: 16,
  },
  taskCost: {
    fontSize: 14,
    fontWeight: '700',
    color: c.text,
    marginStart: Spacing.sm,
  },
  emptyCard: {
    backgroundColor: c.surface,
    borderRadius: Radius.card,
    padding: Spacing.xxxl,
    alignItems: 'center',
    ...cardShadowSm(c),
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: c.text,
    marginBottom: Spacing.xs,
    lineHeight: 22,
  },
  emptySubtitle: {
    fontSize: 14,
    color: c.textSecondary,
    marginBottom: Spacing.lg,
    lineHeight: 19,
  },
  emptyAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    borderRadius: Radius.md,
    backgroundColor: c.primaryLight,
  },
  emptyActionText: {
    fontSize: 14,
    fontWeight: '600',
    color: c.primary,
    lineHeight: 19,
  },
  providersRow: {
    gap: Spacing.md,
    paddingLeft: Spacing.xs,
    paddingRight: Spacing.xs,
  },
  providerCard: {
    minWidth: 140,
    flex: 1,
    maxWidth: 180,
    backgroundColor: c.surface,
    borderRadius: Radius.card,
    padding: Spacing.lg,
    alignItems: 'center',
    ...cardShadowSm(c),
  },
  providerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Spacing.md,
    overflow: 'hidden',
  },
  providerInitial: {
    fontSize: 18,
    fontWeight: '700',
    color: c.text,
  },
  emptyProviderCard: {
    backgroundColor: c.surface,
    borderRadius: Radius.card,
    padding: Spacing.xxl,
    alignItems: 'center',
    ...cardShadowSm(c),
  },
  emptyProviderIcon: {
    width: 44,
    height: 44,
    borderRadius: Radius.xl,
    backgroundColor: c.surfaceAlt,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  emptyProviderTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: c.text,
    marginBottom: Spacing.xs,
    lineHeight: 20,
  },
  emptyProviderSub: {
    fontSize: 13,
    color: c.textSecondary,
    textAlign: 'center' as const,
    lineHeight: 18,
  },
  providerName: {
    fontSize: 13,
    fontWeight: '600',
    color: c.text,
    textAlign: 'center',
    marginBottom: 2,
    lineHeight: 17,
  },
  providerSpecialty: {
    fontSize: 11,
    color: c.textSecondary,
    textAlign: 'center',
    marginBottom: Spacing.sm,
    lineHeight: 15,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  ratingText: {
    fontSize: 12,
    fontWeight: '600',
    color: c.text,
    lineHeight: 16,
  },
});

export default createStyles;
