import { StyleSheet } from 'react-native';
import { ColorScheme } from '@/constants/colors';

const createStyles = (c: ColorScheme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: c.background,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: c.background,
  },
  loadingText: {
    fontSize: 16,
    lineHeight: 22,
    color: c.textSecondary,
  },
  greetingSection: {
    marginBottom: 20,
  },
  greeting: {
    fontSize: 30,
    fontWeight: '800' as const,
    color: c.text,
    letterSpacing: -0.8,
    lineHeight: 36,
  },
  greetingSubtitle: {
    fontSize: 15,
    lineHeight: 21,
    color: c.textSecondary,
    marginTop: 4,
  },
  alertBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.dangerLight,
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
    gap: 12,
  },
  alertIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: c.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  alertContent: {
    flex: 1,
  },
  alertTitle: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: c.danger,
    lineHeight: 19,
  },
  alertSubtitle: {
    fontSize: 12,
    color: c.danger,
    opacity: 0.7,
    marginTop: 1,
    lineHeight: 16,
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 18,
    marginHorizontal: -4,
  },
  quickAction: {
    width: '50%',
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  quickActionInner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.surface,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 14,
    gap: 10,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 1,
    flex: 1,
  },
  quickActionIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quickActionLabel: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: c.text,
    lineHeight: 17,
  },
  budgetCard: {
    backgroundColor: c.surface,
    borderRadius: 18,
    padding: 18,
    marginBottom: 24,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 2,
  },
  budgetTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  budgetLabel: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: c.textSecondary,
    lineHeight: 19,
  },
  budgetRightCol: {
    alignItems: 'flex-end',
  },
  budgetHighlight: {
    fontSize: 20,
    fontWeight: '700' as const,
    lineHeight: 24,
    letterSpacing: -0.3,
  },
  budgetRightSub: {
    fontSize: 11,
    color: c.textTertiary,
    lineHeight: 15,
    marginTop: 1,
  },
  budgetBarBg: {
    height: 6,
    backgroundColor: c.surfaceAlt,
    borderRadius: 3,
    overflow: 'hidden',
  },
  budgetBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  budgetBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  budgetSpent: {
    fontSize: 12,
    color: c.textSecondary,
    lineHeight: 16,
  },
  budgetTotal: {
    fontSize: 12,
    color: c.textTertiary,
    lineHeight: 16,
  },
  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700' as const,
    color: c.text,
    letterSpacing: -0.3,
    lineHeight: 26,
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: c.primary,
    lineHeight: 19,
  },
  taskCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.surface,
    borderRadius: 14,
    padding: 16,
    marginBottom: 8,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 1,
  },
  priorityIndicator: {
    width: 4,
    height: 32,
    borderRadius: 2,
    marginRight: 14,
  },
  taskContent: {
    flex: 1,
  },
  taskTitle: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: c.text,
    marginBottom: 4,
    lineHeight: 20,
  },
  taskMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  metaDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: c.textTertiary,
  },
  taskDate: {
    fontSize: 12,
    color: c.textSecondary,
    lineHeight: 16,
  },
  taskAppliance: {
    fontSize: 12,
    color: c.textTertiary,
    lineHeight: 16,
  },
  taskCost: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: c.text,
    marginLeft: 8,
  },
  emptyCard: {
    backgroundColor: c.surface,
    borderRadius: 16,
    padding: 28,
    alignItems: 'center',
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 1,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: c.text,
    marginBottom: 4,
    lineHeight: 22,
  },
  emptySubtitle: {
    fontSize: 14,
    color: c.textSecondary,
    marginBottom: 16,
    lineHeight: 19,
  },
  emptyAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: c.primaryLight,
  },
  emptyActionText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: c.primary,
    lineHeight: 19,
  },
  providersRow: {
    gap: 12,
    paddingRight: 4,
  },
  providerCard: {
    width: 148,
    backgroundColor: c.surface,
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 1,
  },
  providerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    overflow: 'hidden',
  },
  providerInitial: {
    fontSize: 18,
    fontWeight: '700' as const,
  },
  emptyProviderCard: {
    backgroundColor: c.surface,
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 1,
  },
  emptyProviderIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: c.surfaceAlt,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  emptyProviderTitle: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: c.text,
    marginBottom: 4,
    lineHeight: 20,
  },
  emptyProviderSub: {
    fontSize: 13,
    color: c.textSecondary,
    textAlign: 'center' as const,
    lineHeight: 18,
  },
  providerName: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: c.text,
    textAlign: 'center',
    marginBottom: 2,
    lineHeight: 17,
  },
  providerSpecialty: {
    fontSize: 11,
    color: c.textSecondary,
    textAlign: 'center',
    marginBottom: 8,
    lineHeight: 15,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  ratingText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: c.text,
    lineHeight: 16,
  },
});

export default createStyles;
