import { StyleSheet } from 'react-native';
import { ColorScheme } from '@/constants/colors';
import { Radius, Spacing } from '@/constants/layout';

const createExpenseStyles = (c: ColorScheme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: c.background,
  },
  notFound: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: Spacing.lg,
  },
  notFoundText: {
    fontSize: 16,
    color: c.textTertiary,
  },
  backBtn: {
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    backgroundColor: c.primary,
    borderRadius: Radius.md,
  },
  backBtnText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: c.white,
  },
  typeToggleRow: {
    flexDirection: 'row',
    gap: Spacing.md,
    marginBottom: Spacing.lg,
  },
  typeToggleBtn: {
    flex: 1,
    paddingVertical: Spacing.md,
    borderRadius: Radius.lg,
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.border,
    alignItems: 'center',
  },
  typeToggleBtnActive: {
    backgroundColor: c.primary,
    borderColor: c.primary,
  },
  typeToggleBtnCredit: {
    backgroundColor: c.success,
    borderColor: c.success,
  },
  typeToggleText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: c.textSecondary,
  },
  typeToggleTextActive: {
    color: c.white,
  },
  typeToggleTextCredit: {
    color: c.white,
  },
  amountSection: {
    alignItems: 'center',
    paddingVertical: Spacing.xxxl,
    marginBottom: Spacing.xl,
    backgroundColor: c.surface,
    borderRadius: Radius.cardXl,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: Spacing.md,
    elevation: 2,
  },
  amountLabel: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: c.textSecondary,
    marginBottom: Spacing.md,
    lineHeight: 19,
  },
  amountInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  amountSign: {
    fontSize: 28,
    fontWeight: '300' as const,
    color: c.textTertiary,
    marginRight: Spacing.xs,
  },
  amountInput: {
    fontSize: 38,
    fontWeight: '800' as const,
    color: c.text,
    minWidth: 120,
    textAlign: 'center',
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  categoryChip: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    borderRadius: Radius.pill,
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.border,
  },
  categoryChipText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: c.textSecondary,
    lineHeight: 17,
  },
  paymentGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.xl,
  },
  paymentChip: {
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.cardLg,
    backgroundColor: c.surfaceAlt,
    borderWidth: 1,
    borderColor: c.borderLight,
  },
  paymentChipActive: {
    backgroundColor: c.primary,
    borderColor: c.primary,
  },
  paymentChipText: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: c.textSecondary,
  },
  paymentChipTextActive: {
    color: c.white,
  },
  receiptSection: {
    backgroundColor: c.surface,
    borderRadius: Radius.card,
    padding: Spacing.lg,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: Spacing.sm,
    elevation: 1,
  },
  receiptActions: {
    flexDirection: 'row',
    gap: Spacing.md,
  },
  receiptBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    paddingVertical: Spacing.xl,
    paddingHorizontal: Spacing.lg,
    borderRadius: Radius.lg,
    backgroundColor: c.surfaceAlt,
    borderWidth: 1,
    borderColor: c.borderLight,
  },
  receiptBtnIcon: {
    width: 36,
    height: 36,
    borderRadius: Radius.md,
    justifyContent: 'center',
    alignItems: 'center',
  },
  receiptBtnText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: c.text,
    lineHeight: 17,
  },
  receiptImagesRow: {
    paddingTop: Spacing.xl,
    gap: Spacing.md,
  },
  receiptImageWrap: {
    width: 90,
    height: 110,
    borderRadius: Radius.md,
    overflow: 'hidden',
    backgroundColor: c.surfaceAlt,
  },
  receiptImage: {
    width: '100%',
    height: '100%',
    borderRadius: Radius.md,
  },
  receiptRemoveBtn: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  receiptBadge: {
    position: 'absolute',
    bottom: 4,
    left: 4,
    width: 20,
    height: 20,
    borderRadius: Radius.xs,
    backgroundColor: c.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  providerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: c.surface,
    borderRadius: Radius.xl,
    padding: Spacing.xl,
    marginBottom: Spacing.md,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: Spacing.sm,
    elevation: 1,
  },
  providerHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    flex: 1,
  },
  providerHeaderIcon: {
    width: 38,
    height: 38,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
  },
  providerSubtext: {
    fontSize: 12,
    color: c.textTertiary,
    marginTop: 1,
    lineHeight: 16,
  },
  trustedProPicker: {
    marginBottom: Spacing.md,
  },
  trustedProPickerLabel: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: c.textSecondary,
    marginBottom: Spacing.sm,
    marginLeft: Spacing.xs,
  },
  trustedProChips: {
    gap: Spacing.md,
  },
  trustedProChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    backgroundColor: c.surface,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: c.borderLight,
  },
  trustedProAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#4A7FBF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  trustedProAvatarText: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: c.white,
  },
  trustedProChipName: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: c.text,
    maxWidth: 120,
  },
  clearProBtn: {
    alignSelf: 'flex-start',
    marginBottom: Spacing.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    backgroundColor: c.dangerLight,
    borderRadius: Radius.sm,
  },
  clearProBtnText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: c.danger,
  },
  saveBtn: {
    backgroundColor: c.accent,
    borderRadius: Radius.xl,
    paddingVertical: Spacing.lg,
    alignItems: 'center',
    marginTop: Spacing.xs,
  },
  saveBtnText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: c.white,
    lineHeight: 22,
  },
});

export default createExpenseStyles;
