import { StyleSheet, Platform } from 'react-native';
import { ColorScheme } from '@/constants/colors';

const createStyles = (c: ColorScheme) => StyleSheet.create({
  container: { flex: 1 },
  content: { paddingHorizontal: 20, paddingTop: 8 },
  saveButton: { fontSize: 16, fontWeight: '600' },
  heroSection: { alignItems: 'center', paddingVertical: 24 },
  profileImageContainer: { width: 96, height: 96, borderRadius: 48, marginBottom: 14, position: 'relative' as const },
  profileImage: { width: 96, height: 96, borderRadius: 48 },
  profileImagePlaceholder: { width: 96, height: 96, borderRadius: 48, justifyContent: 'center', alignItems: 'center' },
  cameraButton: { position: 'absolute' as const, bottom: 0, right: 0, width: 30, height: 30, borderRadius: 15, justifyContent: 'center', alignItems: 'center', borderWidth: 2.5 },
  heroTitle: { fontSize: 22, fontWeight: '700', marginBottom: 6 },
  heroSubtitle: { fontSize: 14, textAlign: 'center', lineHeight: 20, paddingHorizontal: 20 },
  section: { marginBottom: 20 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8, paddingHorizontal: 4, paddingVertical: 4 },
  sectionLabel: { fontSize: 13, fontWeight: '600', textTransform: 'uppercase' as const, letterSpacing: 0.8 },
  card: { borderRadius: 16, overflow: 'hidden', shadowColor: c.cardShadow, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 6, elevation: 1 },
  inputRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14 },
  inputIcon: { width: 36, height: 36, borderRadius: 10, justifyContent: 'center', alignItems: 'center', marginRight: 14 },
  inputContent: { flex: 1 },
  inputLabel: { fontSize: 12, fontWeight: '500', marginBottom: 4 },
  textInput: { fontSize: 16, fontWeight: '500', padding: 0, margin: 0 },
  pickerTrigger: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  pickerValue: { fontSize: 16, fontWeight: '500' },
  divider: { height: 1, marginLeft: 66 },
  inlineRow: { flexDirection: 'row', paddingHorizontal: 16, paddingVertical: 14, gap: 12 },
  inlineField: { flex: 2 },
  inlineFieldSmall: { flex: 1 },
  gridRow: { flexDirection: 'row', paddingHorizontal: 16, paddingVertical: 16, gap: 12 },
  gridItem: { flex: 1, alignItems: 'center' },
  gridIcon: { width: 36, height: 36, borderRadius: 10, justifyContent: 'center', alignItems: 'center', marginBottom: 6 },
  gridLabel: { fontSize: 11, fontWeight: '500', marginBottom: 6 },
  gridInput: { fontSize: 20, fontWeight: '700', textAlign: 'center', padding: 0, minWidth: 40 },
  switchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 14 },
  switchLeft: { flexDirection: 'row', alignItems: 'center' },
  switchLabel: { fontSize: 16, fontWeight: '500', marginLeft: 14 },
  notesRow: { flexDirection: 'row', alignItems: 'flex-start', paddingHorizontal: 16, paddingVertical: 14 },
  notesInput: { flex: 1, fontSize: 15, fontWeight: '400', minHeight: 80, padding: 0, margin: 0 },
  saveButtonLarge: { borderRadius: 14, paddingVertical: 16, alignItems: 'center', marginTop: 4 },
  saveButtonLargeText: { fontSize: 16, fontWeight: '700', color: c.white, letterSpacing: 0.3 },
  resetButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderRadius: 14, paddingVertical: 16, gap: 10 },
  resetButtonText: { fontSize: 16, fontWeight: '600' },
  deleteAccountButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderRadius: 14, paddingVertical: 16, gap: 10, marginTop: 12 },
  deleteAccountText: { fontSize: 16, fontWeight: '600' },
  zillowPreviewContainer: { marginTop: 10 },
  zillowPreviewActions: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 8 },
  zillowEditButton: { paddingHorizontal: 14, paddingVertical: 7, borderRadius: 8 },
  zillowEditText: { fontSize: 13, fontWeight: '600' },
  zillowAddButton: { flexDirection: 'row', alignItems: 'center', marginTop: 10, borderRadius: 16, paddingHorizontal: 14, paddingVertical: 14, shadowColor: c.cardShadow, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 6, elevation: 1 },
  zillowAddIconContainer: { width: 34, height: 34, borderRadius: 10, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  zillowAddText: { flex: 1, fontSize: 16, fontWeight: '500' },
  modalOverlay: { flex: 1, backgroundColor: c.overlay, justifyContent: 'flex-end' },
  modalDismissArea: { flex: 1 },
  modalContent: { borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 24, paddingTop: 20, paddingBottom: Platform.OS === 'ios' ? 40 : 24 },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  modalTitle: { fontSize: 20, fontWeight: '700' },
  modalDescription: { fontSize: 14, lineHeight: 20, marginBottom: 18 },
  modalInputContainer: { flexDirection: 'row', alignItems: 'center', borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, gap: 10, marginBottom: 20 },
  modalInput: { flex: 1, fontSize: 15, fontWeight: '400', padding: 0, margin: 0 },
  modalActions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  modalRemoveButton: { paddingHorizontal: 16, paddingVertical: 12, borderRadius: 12 },
  modalRemoveText: { fontSize: 15, fontWeight: '600' },
  modalSaveButton: { paddingHorizontal: 28, paddingVertical: 12, borderRadius: 12 },
  modalSaveButtonDisabled: { opacity: 0.4 },
  modalSaveText: { fontSize: 15, fontWeight: '600' },
  zillowSearchButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: c.primary, borderRadius: 12, paddingVertical: 14, gap: 10, marginBottom: 8 },
  zillowSearchButtonText: { fontSize: 15, fontWeight: '600', color: c.white },
  zillowSearchHint: { fontSize: 12, textAlign: 'center', marginBottom: 14, lineHeight: 17 },
  zillowDividerRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 14, gap: 10 },
  zillowDividerLine: { flex: 1, height: 1 },
  zillowDividerText: { fontSize: 12, fontWeight: '500', textTransform: 'uppercase' as const, letterSpacing: 0.5 },
  householdAvatar: { width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center', marginRight: 14 },
  householdInviteIconContainer: { width: 34, height: 34, borderRadius: 10, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  themeToggleRow: { flexDirection: 'row' as const, gap: 10 },
  themeToggleButton: { flex: 1, flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'center' as const, gap: 6, paddingVertical: 12, borderRadius: 12, borderWidth: 1 },
  themeToggleButtonActive: { borderWidth: 0 },
  themeToggleText: { fontSize: 13, fontWeight: '600' },
  themeToggleTextActive: { fontWeight: '600' as const },
  paletteButton: { flex: 1, alignItems: 'center' as const, justifyContent: 'center' as const, gap: 8, paddingVertical: 14, borderRadius: 12, borderWidth: 2 },
  paletteButtonActive: { borderWidth: 2 },
  paletteSwatch: { width: 28, height: 28, borderRadius: 14 },
  paletteLabel: { fontSize: 12, fontWeight: '600' },
  syncNowButton: { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 8 },
  syncNowText: { fontSize: 13, fontWeight: '600' },
});

export default createStyles;
