import { StyleSheet } from 'react-native';
import { ColorScheme } from '@/constants/colors';
import { Radius, Spacing } from '@/constants/layout';

const createStyles = (c: ColorScheme) => StyleSheet.create({
  container: { flex: 1, backgroundColor: c.background },
  content: { paddingHorizontal: Spacing.xl, paddingTop: Spacing.lg },
  notFound: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  notFoundText: { fontSize: 16, color: c.textTertiary },
  profileHeader: { alignItems: 'center', marginBottom: Spacing.xl },
  avatar: {
    width: 76, height: 76, borderRadius: 38, backgroundColor: c.primary,
    justifyContent: 'center', alignItems: 'center', marginBottom: Spacing.md,
    shadowColor: c.primary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.25, shadowRadius: Spacing.sm, elevation: 4,
  },
  avatarText: { fontSize: 30, fontWeight: '700' as const, color: c.white },
  proName: { fontSize: 22, fontWeight: '800' as const, color: c.text, marginBottom: Spacing.xs, letterSpacing: -0.3 },
  proSpecialty: { fontSize: 15, color: c.textSecondary, lineHeight: 20 },
  nameInput: {
    fontSize: 22, fontWeight: '800' as const, color: c.text, textAlign: 'center' as const,
    marginBottom: Spacing.xs, borderBottomWidth: 1, borderBottomColor: c.primary, paddingBottom: Spacing.xs, minWidth: 200,
  },
  specialtyInput: {
    fontSize: 15, color: c.textSecondary, textAlign: 'center' as const,
    borderBottomWidth: 1, borderBottomColor: c.borderLight, paddingBottom: Spacing.xs, minWidth: 150,
  },
  overallRatingRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, marginTop: Spacing.md },
  overallRatingText: { fontSize: 15, fontWeight: '700' as const, color: c.warning },
  overallRatingLabel: { fontSize: 12, color: c.textTertiary },
  verifiedBadge: {
    flexDirection: 'row', alignItems: 'center', gap: Spacing.xs,
    backgroundColor: c.primaryLight, paddingHorizontal: Spacing.md, paddingVertical: Spacing.xs, borderRadius: Radius.sm, marginTop: Spacing.sm,
  },
  verifiedText: { fontSize: 12, fontWeight: '600' as const, color: c.primary },
  statsRow: { flexDirection: 'row', gap: Spacing.md, marginBottom: Spacing.xl },
  statCard: {
    flex: 1, backgroundColor: c.surface, borderRadius: Radius.xl, padding: Spacing.xl, alignItems: 'center',
    shadowColor: c.cardShadow, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 1, shadowRadius: Spacing.xs, elevation: 1,
  },
  statValue: { fontSize: 16, fontWeight: '800' as const, color: c.text, marginBottom: 2 },
  statLabel: { fontSize: 11, color: c.textTertiary, lineHeight: 15 },
  serviceCatsWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.xs, marginBottom: Spacing.xl, alignItems: 'center' },
  serviceCatChip: { backgroundColor: c.primaryLight, paddingHorizontal: Spacing.md, paddingVertical: 5, borderRadius: Radius.sm },
  serviceCatChipText: { fontSize: 12, fontWeight: '600' as const, color: c.primaryDark },
  editCatsBtn: {
    width: 28, height: 28, borderRadius: Radius.xl, backgroundColor: c.surfaceAlt,
    justifyContent: 'center', alignItems: 'center',
  },
  addServiceInfoBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm,
    backgroundColor: c.primaryLight, borderRadius: Radius.lg, paddingVertical: Spacing.md, marginBottom: Spacing.xl,
    borderWidth: 1, borderColor: c.primary + '30', borderStyle: 'dashed',
  },
  addServiceInfoText: { fontSize: 14, fontWeight: '600' as const, color: c.primary },
  section: { marginBottom: Spacing.xxl },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: Spacing.md },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  sectionTitle: { fontSize: 18, fontWeight: '700' as const, color: c.text, letterSpacing: -0.2 },
  sectionAddBtn: {
    width: 32, height: 32, borderRadius: Radius.md, backgroundColor: c.primaryLight,
    justifyContent: 'center', alignItems: 'center',
  },
  privateBadge: { backgroundColor: c.surfaceAlt, paddingHorizontal: Spacing.sm, paddingVertical: 2, borderRadius: Radius.xs },
  privateBadgeText: {
    fontSize: 10, fontWeight: '600' as const, color: c.textTertiary,
    textTransform: 'uppercase' as const, letterSpacing: 0.5,
  },
  emptyCard: {
    backgroundColor: c.surface, borderRadius: Radius.xl, padding: Spacing.xxl, alignItems: 'center', gap: Spacing.sm,
    borderWidth: 1, borderColor: c.borderLight, borderStyle: 'dashed',
  },
  emptyCardText: { fontSize: 13, color: c.textTertiary, textAlign: 'center' as const, lineHeight: 18 },
  ratingsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.md },
  ratingCard: {
    backgroundColor: c.surface, borderRadius: Radius.xl, padding: Spacing.xl, width: '48%' as any,
    shadowColor: c.cardShadow, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 1, shadowRadius: Spacing.xs, elevation: 1,
  },
  ratingCardTop: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, marginBottom: Spacing.sm },
  ratingSourceDot: { width: 8, height: 8, borderRadius: 4 },
  ratingSourceLabel: { fontSize: 12, fontWeight: '600' as const, color: c.textSecondary, flex: 1 },
  ratingCardBody: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, marginBottom: Spacing.xs },
  ratingValue: { fontSize: 22, fontWeight: '800' as const, color: c.text },
  ratingReviewCount: { fontSize: 11, color: c.textTertiary, marginTop: 2 },
  ratingLinkBtn: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, marginTop: Spacing.xs },
  ratingLinkText: { fontSize: 11, fontWeight: '600' as const, color: c.primary },
  card: {
    backgroundColor: c.surface, borderRadius: Radius.card, overflow: 'hidden',
    shadowColor: c.cardShadow, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 1, shadowRadius: Spacing.sm, elevation: 1,
  },
  contactRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, paddingHorizontal: Spacing.lg, paddingVertical: Spacing.xl },
  contactText: { flex: 1, fontSize: 15, color: c.text, lineHeight: 20 },
  noContactText: { fontSize: 14, color: c.textTertiary, fontStyle: 'italic' as const },
  editRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, paddingHorizontal: Spacing.lg, paddingVertical: Spacing.md },
  editInput: { flex: 1, fontSize: 15, color: c.text, lineHeight: 20, padding: 0 },
  divider: { height: 1, backgroundColor: c.borderLight, marginLeft: 44 },
  linkedApplianceCard: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: c.surface, borderRadius: Radius.xl, marginBottom: Spacing.sm,
    shadowColor: c.cardShadow, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 1, shadowRadius: Spacing.xs, elevation: 1, overflow: 'hidden',
  },
  linkedApplianceMain: { flex: 1, flexDirection: 'row', alignItems: 'center', padding: Spacing.xl },
  applianceDot: { width: 10, height: 10, borderRadius: 5, marginRight: Spacing.md },
  applianceInfo: { flex: 1 },
  applianceName: { fontSize: 15, fontWeight: '600' as const, color: c.text, marginBottom: 2 },
  applianceMeta: { fontSize: 12, color: c.textTertiary, lineHeight: 16 },
  unlinkBtn: { paddingHorizontal: Spacing.xl, paddingVertical: Spacing.xl, justifyContent: 'center', alignItems: 'center' },
  noteCard: {
    backgroundColor: c.surface, borderRadius: Radius.xl, padding: Spacing.xl, marginBottom: Spacing.sm,
    shadowColor: c.cardShadow, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 1, shadowRadius: Spacing.xs, elevation: 1,
  },
  noteText: { fontSize: 14, color: c.text, lineHeight: 20, marginBottom: Spacing.sm },
  noteFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  noteDate: { fontSize: 11, color: c.textTertiary },
  noteActions: { flexDirection: 'row', gap: Spacing.lg },
  noteEditWrap: { gap: Spacing.sm },
  noteEditInput: {
    fontSize: 14, color: c.text, lineHeight: 20, borderWidth: 1, borderColor: c.primary,
    borderRadius: Radius.md, padding: Spacing.md, minHeight: 60, textAlignVertical: 'top' as const,
  },
  noteEditActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: Spacing.sm },
  noteEditCancelBtn: { paddingHorizontal: Spacing.xl, paddingVertical: Spacing.xs, borderRadius: Radius.sm, backgroundColor: c.surfaceAlt },
  noteEditCancelText: { fontSize: 13, fontWeight: '600' as const, color: c.textSecondary },
  noteEditSaveBtn: { paddingHorizontal: Spacing.xl, paddingVertical: Spacing.xs, borderRadius: Radius.sm, backgroundColor: c.primary },
  noteEditSaveText: { fontSize: 13, fontWeight: '600' as const, color: c.white },
  addNoteWrap: {
    flexDirection: 'row', alignItems: 'flex-end', gap: Spacing.sm, backgroundColor: c.surface, borderRadius: Radius.xl, padding: Spacing.md,
    shadowColor: c.cardShadow, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 1, shadowRadius: Spacing.xs, elevation: 1,
  },
  addNoteInput: { flex: 1, fontSize: 14, color: c.text, lineHeight: 20, padding: 0, maxHeight: 80 },
  addNoteBtn: { width: 34, height: 34, borderRadius: Radius.md, backgroundColor: c.primary, justifyContent: 'center', alignItems: 'center' },
  expenseRow: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: c.surface, borderRadius: Radius.xl, padding: Spacing.xl, marginBottom: Spacing.sm,
    shadowColor: c.cardShadow, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 1, shadowRadius: Spacing.xs, elevation: 1,
  },
  expenseDot: { width: 8, height: 8, borderRadius: 4, marginRight: Spacing.md },
  expenseInfo: { flex: 1 },
  expenseDesc: { fontSize: 15, fontWeight: '600' as const, color: c.text, marginBottom: 2, lineHeight: 20 },
  expenseMeta: { fontSize: 12, color: c.textTertiary, lineHeight: 16 },
  expenseAmount: { fontSize: 15, fontWeight: '700' as const, color: c.danger, marginLeft: Spacing.sm },
  deleteCard: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm,
    backgroundColor: c.dangerLight, borderRadius: Radius.xl, paddingVertical: Spacing.xl, marginBottom: Spacing.xl,
  },
  deleteText: { fontSize: 15, fontWeight: '600' as const, color: c.danger },
  modalContainer: { flex: 1, backgroundColor: c.background, paddingHorizontal: Spacing.xl, paddingTop: Spacing.xl },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: Spacing.xs },
  modalTitle: { fontSize: 20, fontWeight: '800' as const, color: c.text, letterSpacing: -0.3 },
  modalSubtitle: { fontSize: 14, color: c.textTertiary, marginBottom: Spacing.xl, lineHeight: 20 },
  modalApplianceRow: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: c.surface, borderRadius: Radius.xl, padding: Spacing.xl, marginBottom: Spacing.sm, gap: Spacing.md,
  },
  modalApplianceDot: { width: 12, height: 12, borderRadius: 6 },
  modalApplianceName: { fontSize: 15, fontWeight: '600' as const, color: c.text },
  modalApplianceSub: { fontSize: 12, color: c.textTertiary, marginTop: 2 },
  modalEmpty: { padding: 30, alignItems: 'center' },
  modalEmptyText: { fontSize: 14, color: c.textTertiary },
  modalFieldLabel: {
    fontSize: 13, fontWeight: '600' as const, color: c.textSecondary, marginBottom: Spacing.sm, marginTop: Spacing.lg,
    textTransform: 'uppercase' as const, letterSpacing: 0.5,
  },
  modalInput: {
    backgroundColor: c.surface, borderRadius: Radius.lg, padding: Spacing.xl, fontSize: 15, color: c.text,
    borderWidth: 1, borderColor: c.borderLight,
  },
  modalSaveBtn: { backgroundColor: c.primary, borderRadius: Radius.xl, paddingVertical: Spacing.lg, alignItems: 'center', marginTop: Spacing.xxl },
  modalSaveBtnText: { fontSize: 16, fontWeight: '700' as const, color: c.white },
  sourceChipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  sourceChip: { paddingHorizontal: Spacing.xl, paddingVertical: Spacing.sm, borderRadius: Radius.md, backgroundColor: c.surfaceAlt },
  sourceChipText: { fontSize: 13, fontWeight: '600' as const, color: c.text },
  serviceCatGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  serviceCatOption: {
    paddingHorizontal: Spacing.xl, paddingVertical: Spacing.sm, borderRadius: Radius.md,
    backgroundColor: c.surfaceAlt, borderWidth: 1, borderColor: c.borderLight,
  },
  serviceCatOptionActive: { backgroundColor: c.primaryLight, borderColor: c.primary },
  serviceCatOptionText: { fontSize: 13, fontWeight: '600' as const, color: c.textSecondary },
  serviceCatOptionTextActive: { color: c.primaryDark },
  radiusWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  radiusChip: {
    paddingHorizontal: Spacing.lg, paddingVertical: Spacing.sm, borderRadius: Radius.md,
    backgroundColor: c.surfaceAlt, borderWidth: 1, borderColor: c.borderLight,
  },
  radiusChipActive: { backgroundColor: c.primaryLight, borderColor: c.primary },
  radiusChipText: { fontSize: 13, fontWeight: '600' as const, color: c.textSecondary },
  radiusChipTextActive: { color: c.primary },
});

export default createStyles;
