import { StyleSheet } from 'react-native';
import Colors from '@/constants/colors';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  content: { paddingHorizontal: 20, paddingTop: 16 },
  notFound: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  notFoundText: { fontSize: 16, color: Colors.textTertiary },
  profileHeader: { alignItems: 'center', marginBottom: 20 },
  avatar: {
    width: 76, height: 76, borderRadius: 38, backgroundColor: '#4A7FBF',
    justifyContent: 'center', alignItems: 'center', marginBottom: 12,
    shadowColor: '#4A7FBF', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.25, shadowRadius: 8, elevation: 4,
  },
  avatarText: { fontSize: 30, fontWeight: '700' as const, color: Colors.white },
  proName: { fontSize: 22, fontWeight: '800' as const, color: Colors.text, marginBottom: 4, letterSpacing: -0.3 },
  proSpecialty: { fontSize: 15, color: Colors.textSecondary, lineHeight: 20 },
  nameInput: {
    fontSize: 22, fontWeight: '800' as const, color: Colors.text, textAlign: 'center' as const,
    marginBottom: 4, borderBottomWidth: 1, borderBottomColor: Colors.primary, paddingBottom: 4, minWidth: 200,
  },
  specialtyInput: {
    fontSize: 15, color: Colors.textSecondary, textAlign: 'center' as const,
    borderBottomWidth: 1, borderBottomColor: Colors.borderLight, paddingBottom: 4, minWidth: 150,
  },
  overallRatingRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 10 },
  overallRatingText: { fontSize: 15, fontWeight: '700' as const, color: '#F5A623' },
  overallRatingLabel: { fontSize: 12, color: Colors.textTertiary },
  verifiedBadge: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: Colors.primaryLight, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8, marginTop: 8,
  },
  verifiedText: { fontSize: 12, fontWeight: '600' as const, color: Colors.primary },
  statsRow: { flexDirection: 'row', gap: 10, marginBottom: 20 },
  statCard: {
    flex: 1, backgroundColor: Colors.surface, borderRadius: 14, padding: 14, alignItems: 'center',
    shadowColor: Colors.cardShadow, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 1, shadowRadius: 6, elevation: 1,
  },
  statValue: { fontSize: 16, fontWeight: '800' as const, color: Colors.text, marginBottom: 2 },
  statLabel: { fontSize: 11, color: Colors.textTertiary, lineHeight: 15 },
  serviceCatsWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 20, alignItems: 'center' },
  serviceCatChip: { backgroundColor: Colors.primaryLight, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8 },
  serviceCatChipText: { fontSize: 12, fontWeight: '600' as const, color: Colors.primaryDark },
  editCatsBtn: {
    width: 28, height: 28, borderRadius: 14, backgroundColor: Colors.surfaceAlt,
    justifyContent: 'center', alignItems: 'center',
  },
  addServiceInfoBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8,
    backgroundColor: Colors.primaryLight, borderRadius: 12, paddingVertical: 12, marginBottom: 20,
    borderWidth: 1, borderColor: Colors.primary + '30', borderStyle: 'dashed',
  },
  addServiceInfoText: { fontSize: 14, fontWeight: '600' as const, color: Colors.primary },
  section: { marginBottom: 24 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  sectionTitle: { fontSize: 18, fontWeight: '700' as const, color: Colors.text, letterSpacing: -0.2 },
  sectionAddBtn: {
    width: 32, height: 32, borderRadius: 10, backgroundColor: Colors.primaryLight,
    justifyContent: 'center', alignItems: 'center',
  },
  privateBadge: { backgroundColor: Colors.surfaceAlt, paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6 },
  privateBadgeText: {
    fontSize: 10, fontWeight: '600' as const, color: Colors.textTertiary,
    textTransform: 'uppercase' as const, letterSpacing: 0.5,
  },
  emptyCard: {
    backgroundColor: Colors.surface, borderRadius: 14, padding: 24, alignItems: 'center', gap: 8,
    borderWidth: 1, borderColor: Colors.borderLight, borderStyle: 'dashed',
  },
  emptyCardText: { fontSize: 13, color: Colors.textTertiary, textAlign: 'center' as const, lineHeight: 18 },
  ratingsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  ratingCard: {
    backgroundColor: Colors.surface, borderRadius: 14, padding: 14, width: '48%' as any,
    shadowColor: Colors.cardShadow, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 1, shadowRadius: 6, elevation: 1,
  },
  ratingCardTop: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 8 },
  ratingSourceDot: { width: 8, height: 8, borderRadius: 4 },
  ratingSourceLabel: { fontSize: 12, fontWeight: '600' as const, color: Colors.textSecondary, flex: 1 },
  ratingCardBody: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
  ratingValue: { fontSize: 22, fontWeight: '800' as const, color: Colors.text },
  ratingReviewCount: { fontSize: 11, color: Colors.textTertiary, marginTop: 2 },
  ratingLinkBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 6 },
  ratingLinkText: { fontSize: 11, fontWeight: '600' as const, color: Colors.primary },
  card: {
    backgroundColor: Colors.surface, borderRadius: 16, overflow: 'hidden',
    shadowColor: Colors.cardShadow, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 1, shadowRadius: 8, elevation: 1,
  },
  contactRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16, paddingVertical: 14 },
  contactText: { flex: 1, fontSize: 15, color: Colors.text, lineHeight: 20 },
  noContactText: { fontSize: 14, color: Colors.textTertiary, fontStyle: 'italic' as const },
  editRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16, paddingVertical: 12 },
  editInput: { flex: 1, fontSize: 15, color: Colors.text, lineHeight: 20, padding: 0 },
  divider: { height: 1, backgroundColor: Colors.borderLight, marginLeft: 44 },
  linkedApplianceCard: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.surface, borderRadius: 14, marginBottom: 8,
    shadowColor: Colors.cardShadow, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 1, shadowRadius: 4, elevation: 1, overflow: 'hidden',
  },
  linkedApplianceMain: { flex: 1, flexDirection: 'row', alignItems: 'center', padding: 14 },
  applianceDot: { width: 10, height: 10, borderRadius: 5, marginRight: 12 },
  applianceInfo: { flex: 1 },
  applianceName: { fontSize: 15, fontWeight: '600' as const, color: Colors.text, marginBottom: 2 },
  applianceMeta: { fontSize: 12, color: Colors.textTertiary, lineHeight: 16 },
  unlinkBtn: { paddingHorizontal: 14, paddingVertical: 14, justifyContent: 'center', alignItems: 'center' },
  noteCard: {
    backgroundColor: Colors.surface, borderRadius: 14, padding: 14, marginBottom: 8,
    shadowColor: Colors.cardShadow, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 1, shadowRadius: 4, elevation: 1,
  },
  noteText: { fontSize: 14, color: Colors.text, lineHeight: 20, marginBottom: 8 },
  noteFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  noteDate: { fontSize: 11, color: Colors.textTertiary },
  noteActions: { flexDirection: 'row', gap: 16 },
  noteEditWrap: { gap: 8 },
  noteEditInput: {
    fontSize: 14, color: Colors.text, lineHeight: 20, borderWidth: 1, borderColor: Colors.primary,
    borderRadius: 10, padding: 10, minHeight: 60, textAlignVertical: 'top' as const,
  },
  noteEditActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8 },
  noteEditCancelBtn: { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 8, backgroundColor: Colors.surfaceAlt },
  noteEditCancelText: { fontSize: 13, fontWeight: '600' as const, color: Colors.textSecondary },
  noteEditSaveBtn: { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 8, backgroundColor: Colors.primary },
  noteEditSaveText: { fontSize: 13, fontWeight: '600' as const, color: Colors.white },
  addNoteWrap: {
    flexDirection: 'row', alignItems: 'flex-end', gap: 8, backgroundColor: Colors.surface, borderRadius: 14, padding: 12,
    shadowColor: Colors.cardShadow, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 1, shadowRadius: 4, elevation: 1,
  },
  addNoteInput: { flex: 1, fontSize: 14, color: Colors.text, lineHeight: 20, padding: 0, maxHeight: 80 },
  addNoteBtn: { width: 34, height: 34, borderRadius: 10, backgroundColor: Colors.primary, justifyContent: 'center', alignItems: 'center' },
  expenseRow: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.surface, borderRadius: 14, padding: 14, marginBottom: 8,
    shadowColor: Colors.cardShadow, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 1, shadowRadius: 4, elevation: 1,
  },
  expenseDot: { width: 8, height: 8, borderRadius: 4, marginRight: 12 },
  expenseInfo: { flex: 1 },
  expenseDesc: { fontSize: 15, fontWeight: '600' as const, color: Colors.text, marginBottom: 2, lineHeight: 20 },
  expenseMeta: { fontSize: 12, color: Colors.textTertiary, lineHeight: 16 },
  expenseAmount: { fontSize: 15, fontWeight: '700' as const, color: Colors.danger, marginLeft: 8 },
  deleteCard: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8,
    backgroundColor: Colors.dangerLight, borderRadius: 14, paddingVertical: 14, marginBottom: 20,
  },
  deleteText: { fontSize: 15, fontWeight: '600' as const, color: Colors.danger },
  modalContainer: { flex: 1, backgroundColor: Colors.background, paddingHorizontal: 20, paddingTop: 20 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  modalTitle: { fontSize: 20, fontWeight: '800' as const, color: Colors.text, letterSpacing: -0.3 },
  modalSubtitle: { fontSize: 14, color: Colors.textTertiary, marginBottom: 20, lineHeight: 20 },
  modalApplianceRow: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.surface, borderRadius: 14, padding: 14, marginBottom: 8, gap: 12,
  },
  modalApplianceDot: { width: 12, height: 12, borderRadius: 6 },
  modalApplianceName: { fontSize: 15, fontWeight: '600' as const, color: Colors.text },
  modalApplianceSub: { fontSize: 12, color: Colors.textTertiary, marginTop: 2 },
  modalEmpty: { padding: 30, alignItems: 'center' },
  modalEmptyText: { fontSize: 14, color: Colors.textTertiary },
  modalFieldLabel: {
    fontSize: 13, fontWeight: '600' as const, color: Colors.textSecondary, marginBottom: 8, marginTop: 16,
    textTransform: 'uppercase' as const, letterSpacing: 0.5,
  },
  modalInput: {
    backgroundColor: Colors.surface, borderRadius: 12, padding: 14, fontSize: 15, color: Colors.text,
    borderWidth: 1, borderColor: Colors.borderLight,
  },
  modalSaveBtn: { backgroundColor: Colors.primary, borderRadius: 14, paddingVertical: 16, alignItems: 'center', marginTop: 24 },
  modalSaveBtnText: { fontSize: 16, fontWeight: '700' as const, color: Colors.white },
  sourceChipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  sourceChip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 10, backgroundColor: Colors.surfaceAlt },
  sourceChipText: { fontSize: 13, fontWeight: '600' as const, color: Colors.text },
  serviceCatGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  serviceCatOption: {
    paddingHorizontal: 14, paddingVertical: 8, borderRadius: 10,
    backgroundColor: Colors.surfaceAlt, borderWidth: 1, borderColor: Colors.borderLight,
  },
  serviceCatOptionActive: { backgroundColor: Colors.primaryLight, borderColor: Colors.primary },
  serviceCatOptionText: { fontSize: 13, fontWeight: '600' as const, color: Colors.textSecondary },
  serviceCatOptionTextActive: { color: Colors.primaryDark },
  radiusWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  radiusChip: {
    paddingHorizontal: 16, paddingVertical: 8, borderRadius: 10,
    backgroundColor: Colors.surfaceAlt, borderWidth: 1, borderColor: Colors.borderLight,
  },
  radiusChipActive: { backgroundColor: '#E8F0FE', borderColor: '#4A7FBF' },
  radiusChipText: { fontSize: 13, fontWeight: '600' as const, color: Colors.textSecondary },
  radiusChipTextActive: { color: '#4A7FBF' },
});
