import { StyleSheet } from 'react-native';
import Colors from '@/constants/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  headerBtn: {
    padding: 2,
  },
  notFound: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notFoundText: {
    fontSize: 16,
    color: Colors.textSecondary,
  },
  header: {
    marginBottom: 20,
  },
  statusRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
    flexWrap: 'wrap',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600' as const,
    lineHeight: 16,
  },
  priorityBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  priorityText: {
    fontSize: 12,
    fontWeight: '600' as const,
    lineHeight: 16,
  },
  title: {
    fontSize: 26,
    fontWeight: '700' as const,
    color: Colors.text,
    lineHeight: 32,
    letterSpacing: -0.3,
    marginBottom: 8,
  },
  titleCompleted: {
    textDecorationLine: 'line-through',
    color: Colors.textSecondary,
  },
  description: {
    fontSize: 15,
    color: Colors.textSecondary,
    lineHeight: 22,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  infoCard: {
    flex: 1,
    minWidth: 140,
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 14,
    shadowColor: Colors.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 1,
  },
  infoIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: Colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  infoLabel: {
    fontSize: 11,
    fontWeight: '500' as const,
    color: Colors.textTertiary,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
    marginBottom: 4,
    lineHeight: 14,
  },
  infoValue: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: Colors.text,
    lineHeight: 19,
  },
  infoSub: {
    fontSize: 12,
    color: Colors.textSecondary,
    marginTop: 2,
    lineHeight: 16,
  },
  applianceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
    shadowColor: Colors.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 1,
  },
  applianceIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  applianceInfo: { flex: 1 },
  applianceLabel: {
    fontSize: 10,
    fontWeight: '600' as const,
    color: Colors.textTertiary,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
    lineHeight: 13,
    marginBottom: 2,
  },
  applianceName: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: Colors.text,
    lineHeight: 20,
  },
  applianceMeta: {
    fontSize: 12,
    color: Colors.textSecondary,
    lineHeight: 16,
    marginTop: 1,
  },
  notesSection: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 16,
    marginBottom: 20,
    shadowColor: Colors.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 1,
  },
  notesSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  notesTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  notesSectionTitle: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: Colors.text,
    lineHeight: 20,
  },
  addNoteBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: Colors.surfaceAlt,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noteInputWrap: { overflow: 'hidden', marginBottom: 10 },
  noteInputCard: { flexDirection: 'row', alignItems: 'flex-end', gap: 8 },
  noteInput: {
    flex: 1,
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 12,
    padding: 12,
    paddingTop: 12,
    fontSize: 14,
    color: Colors.text,
    minHeight: 60,
    maxHeight: 100,
    lineHeight: 20,
  },
  sendNoteBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 2,
  },
  sendNoteBtnDisabled: { backgroundColor: Colors.surfaceAlt },
  emptyNotes: { paddingVertical: 16, alignItems: 'center' },
  emptyNotesText: { fontSize: 13, color: Colors.textTertiary },
  noteItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: Colors.borderLight,
    gap: 8,
  },
  noteDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: Colors.primary, marginTop: 6 },
  noteText: { flex: 1, fontSize: 14, color: Colors.text, lineHeight: 20 },
  noteDeleteBtn: { padding: 4, marginTop: 2 },
  linkSection: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    shadowColor: Colors.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 1,
  },
  linkSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  linkTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  linkSectionTitle: { fontSize: 15, fontWeight: '600' as const, color: Colors.text, lineHeight: 20 },
  addLinkBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: Colors.surfaceAlt,
    justifyContent: 'center',
    alignItems: 'center',
  },
  linkInputWrap: { overflow: 'hidden' },
  linkInputCard: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  linkInput: {
    flex: 1,
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: Colors.text,
    lineHeight: 20,
  },
  saveLinkBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveLinkBtnDisabled: { backgroundColor: Colors.surfaceAlt },
  linkDisplayCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.primaryLight,
    borderRadius: 12,
    padding: 12,
    gap: 8,
  },
  linkDisplayContent: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 10 },
  linkIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: Colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  linkUrl: { flex: 1, fontSize: 13, color: Colors.primary, lineHeight: 18 },
  linkRemoveBtn: { padding: 4 },
  emptyLinkPrompt: { paddingVertical: 12, alignItems: 'center' },
  emptyLinkText: { fontSize: 13, color: Colors.textTertiary },
  amazonSearchBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
    paddingVertical: 11,
    paddingHorizontal: 14,
    backgroundColor: '#FFF8ED',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFE4B5',
  },
  amazonSearchText: { fontSize: 14, fontWeight: '600' as const, color: '#C47E00', lineHeight: 19 },
  actionsSection: { gap: 10 },
  completeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colors.primary,
    borderRadius: 14,
    paddingVertical: 16,
  },
  completeBtnText: { fontSize: 16, fontWeight: '700' as const, color: Colors.white, lineHeight: 22 },
  restoreBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colors.primary,
    borderRadius: 14,
    paddingVertical: 16,
  },
  restoreBtnText: { fontSize: 16, fontWeight: '700' as const, color: Colors.white, lineHeight: 22 },
  archiveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 14,
    paddingVertical: 14,
  },
  archiveBtnText: { fontSize: 15, fontWeight: '600' as const, color: Colors.textSecondary, lineHeight: 20 },
  deleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colors.dangerLight,
    borderRadius: 14,
    paddingVertical: 14,
  },
  deleteBtnText: { fontSize: 15, fontWeight: '600' as const, color: Colors.danger, lineHeight: 20 },
  editContent: { paddingHorizontal: 20, paddingTop: 16 },
  editSaveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colors.primary,
    borderRadius: 14,
    paddingVertical: 16,
    marginTop: 4,
  },
  editSaveBtnText: { fontSize: 16, fontWeight: '700' as const, color: Colors.white, lineHeight: 22 },
  editCancelBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    paddingVertical: 14,
    marginTop: 10,
    backgroundColor: Colors.surfaceAlt,
  },
  editCancelBtnText: { fontSize: 15, fontWeight: '600' as const, color: Colors.textSecondary, lineHeight: 20 },
  proSection: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    shadowColor: Colors.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 1,
  },
  proSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  proTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  proSectionTitle: { fontSize: 15, fontWeight: '600' as const, color: Colors.text, lineHeight: 20 },
  proRemoveBtn: { padding: 4 },
  proCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.primaryLight,
    borderRadius: 12,
    padding: 12,
    gap: 10,
  },
  proAvatarWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: Colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  proCardInfo: { flex: 1 },
  proCardName: { fontSize: 15, fontWeight: '600' as const, color: Colors.text, lineHeight: 20 },
  proCardSpecialty: { fontSize: 12, color: Colors.textSecondary, lineHeight: 16, marginTop: 1 },
  proCardPhoneRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 3 },
  proCardPhone: { fontSize: 12, color: Colors.textTertiary, lineHeight: 16 },
  proRatingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: Colors.surface,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  proRatingText: { fontSize: 12, fontWeight: '600' as const, color: Colors.text, lineHeight: 16 },
  proEmptyState: { alignItems: 'center', paddingVertical: 8, gap: 12 },
  proEmptyText: { fontSize: 13, color: Colors.textTertiary },
  proEmptyActions: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  proSelectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: Colors.primaryLight,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
  },
  proSelectBtnText: { fontSize: 14, fontWeight: '600' as const, color: Colors.primary, lineHeight: 19 },
  findProBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: Colors.primary,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
  },
  findProBtnText: { fontSize: 14, fontWeight: '600' as const, color: Colors.white, lineHeight: 19 },
  proPickerWrap: { gap: 8 },
  proPickerLabel: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: Colors.textTertiary,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  proPickerList: { maxHeight: 200 },
  proPickerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  proPickerAvatar: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: Colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  proPickerInfo: { flex: 1 },
  proPickerName: { fontSize: 14, fontWeight: '600' as const, color: Colors.text, lineHeight: 19 },
  proPickerSpecialty: { fontSize: 12, color: Colors.textSecondary, lineHeight: 16 },
  proPickerCancelBtn: { alignItems: 'center', paddingVertical: 10, marginTop: 4 },
  proPickerCancelText: { fontSize: 14, fontWeight: '500' as const, color: Colors.textSecondary },
  proPickerEmpty: { alignItems: 'center', gap: 12, paddingVertical: 8 },
  proPickerEmptyText: { fontSize: 13, color: Colors.textTertiary },
});
