import { StyleSheet } from 'react-native';
import { ColorScheme } from '@/constants/colors';
import { Radius, Spacing } from '@/constants/layout';

const createStyles = (c: ColorScheme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: c.background,
  },
  content: {
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.sm,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xl,
  },
  headerBtn: {
    padding: 2,
  },
  notFound: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notFoundText: {
    fontSize: 16,
    color: c.textSecondary,
  },
  header: {
    marginBottom: Spacing.xl,
  },
  statusRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginBottom: Spacing.xl,
    flexWrap: 'wrap',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: Spacing.md,
    paddingVertical: 5,
    borderRadius: Radius.sm,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600' as const,
    lineHeight: 16,
  },
  priorityBadge: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 5,
    borderRadius: Radius.sm,
  },
  priorityText: {
    fontSize: 12,
    fontWeight: '600' as const,
    lineHeight: 16,
  },
  title: {
    fontSize: 26,
    fontWeight: '700' as const,
    color: c.text,
    lineHeight: 32,
    letterSpacing: -0.3,
    marginBottom: Spacing.sm,
  },
  titleCompleted: {
    textDecorationLine: 'line-through',
    color: c.textSecondary,
  },
  description: {
    fontSize: 15,
    color: c.textSecondary,
    lineHeight: 22,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.md,
    marginBottom: Spacing.lg,
  },
  infoCard: {
    flex: 1,
    minWidth: 140,
    backgroundColor: c.surface,
    borderRadius: Radius.xl,
    padding: Spacing.xl,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: Spacing.xs,
    elevation: 1,
  },
  infoIconWrap: {
    width: 32,
    height: 32,
    borderRadius: Radius.md,
    backgroundColor: c.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  infoLabel: {
    fontSize: 11,
    fontWeight: '500' as const,
    color: c.textTertiary,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
    marginBottom: Spacing.xs,
    lineHeight: 14,
  },
  infoValue: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: c.text,
    lineHeight: 19,
  },
  infoSub: {
    fontSize: 12,
    color: c.textSecondary,
    marginTop: 2,
    lineHeight: 16,
  },
  applianceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.surface,
    borderRadius: Radius.xl,
    padding: Spacing.xl,
    marginBottom: Spacing.lg,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: Spacing.xs,
    elevation: 1,
  },
  applianceIconWrap: {
    width: 40,
    height: 40,
    borderRadius: Radius.lg,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Spacing.md,
  },
  applianceInfo: { flex: 1 },
  applianceLabel: {
    fontSize: 10,
    fontWeight: '600' as const,
    color: c.textTertiary,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
    lineHeight: 13,
    marginBottom: 2,
  },
  applianceName: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: c.text,
    lineHeight: 20,
  },
  applianceMeta: {
    fontSize: 12,
    color: c.textSecondary,
    lineHeight: 16,
    marginTop: 1,
  },
  notesSection: {
    backgroundColor: c.surface,
    borderRadius: Radius.xl,
    padding: Spacing.lg,
    marginBottom: Spacing.xl,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: Spacing.xs,
    elevation: 1,
  },
  notesSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  notesTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  notesSectionTitle: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: c.text,
    lineHeight: 20,
  },
  addNoteBtn: {
    width: 32,
    height: 32,
    borderRadius: Radius.md,
    backgroundColor: c.surfaceAlt,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noteInputWrap: { overflow: 'hidden', marginBottom: Spacing.md },
  noteInputCard: { flexDirection: 'row', alignItems: 'flex-end', gap: Spacing.sm },
  noteInput: {
    flex: 1,
    backgroundColor: c.surfaceAlt,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    paddingTop: Spacing.md,
    fontSize: 14,
    color: c.text,
    minHeight: 60,
    maxHeight: 100,
    lineHeight: 20,
  },
  sendNoteBtn: {
    width: 36,
    height: 36,
    borderRadius: Radius.md,
    backgroundColor: c.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 2,
  },
  sendNoteBtnDisabled: { backgroundColor: c.surfaceAlt },
  emptyNotes: { paddingVertical: Spacing.lg, alignItems: 'center' },
  emptyNotesText: { fontSize: 13, color: c.textTertiary },
  noteItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: c.borderLight,
    gap: Spacing.sm,
  },
  noteDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: c.primary, marginTop: 6 },
  noteText: { flex: 1, fontSize: 14, color: c.text, lineHeight: 20 },
  noteDeleteBtn: { padding: Spacing.xs, marginTop: 2 },
  linkSection: {
    backgroundColor: c.surface,
    borderRadius: Radius.xl,
    padding: Spacing.lg,
    marginBottom: Spacing.lg,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: Spacing.xs,
    elevation: 1,
  },
  linkSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  linkTitleRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
  linkSectionTitle: { fontSize: 15, fontWeight: '600' as const, color: c.text, lineHeight: 20 },
  addLinkBtn: {
    width: 32,
    height: 32,
    borderRadius: Radius.md,
    backgroundColor: c.surfaceAlt,
    justifyContent: 'center',
    alignItems: 'center',
  },
  linkInputWrap: { overflow: 'hidden' },
  linkInputCard: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  linkInput: {
    flex: 1,
    backgroundColor: c.surfaceAlt,
    borderRadius: Radius.lg,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    fontSize: 14,
    color: c.text,
    lineHeight: 20,
  },
  saveLinkBtn: {
    width: 36,
    height: 36,
    borderRadius: Radius.md,
    backgroundColor: c.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveLinkBtnDisabled: { backgroundColor: c.surfaceAlt },
  linkDisplayCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.primaryLight,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    gap: Spacing.sm,
  },
  linkDisplayContent: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  linkIconWrap: {
    width: 28,
    height: 28,
    borderRadius: Radius.sm,
    backgroundColor: c.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  linkUrl: { flex: 1, fontSize: 13, color: c.primary, lineHeight: 18 },
  linkRemoveBtn: { padding: Spacing.xs },
  emptyLinkPrompt: { paddingVertical: Spacing.md, alignItems: 'center' },
  emptyLinkText: { fontSize: 13, color: c.textTertiary },
  amazonSearchBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: Spacing.md,
    paddingVertical: 11,
    paddingHorizontal: Spacing.xl,
    backgroundColor: c.warningLight,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: c.warning + '40',
  },
  amazonSearchText: { fontSize: 14, fontWeight: '600' as const, color: c.warning, lineHeight: 19 },
  actionsSection: { gap: Spacing.md },
  completeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    backgroundColor: c.primary,
    borderRadius: Radius.xl,
    paddingVertical: Spacing.lg,
  },
  completeBtnText: { fontSize: 16, fontWeight: '700' as const, color: c.white, lineHeight: 22 },
  restoreBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    backgroundColor: c.primary,
    borderRadius: Radius.xl,
    paddingVertical: Spacing.lg,
  },
  restoreBtnText: { fontSize: 16, fontWeight: '700' as const, color: c.white, lineHeight: 22 },
  archiveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    backgroundColor: c.surfaceAlt,
    borderRadius: Radius.xl,
    paddingVertical: Spacing.xl,
  },
  archiveBtnText: { fontSize: 15, fontWeight: '600' as const, color: c.textSecondary, lineHeight: 20 },
  deleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    backgroundColor: c.dangerLight,
    borderRadius: Radius.xl,
    paddingVertical: Spacing.xl,
  },
  deleteBtnText: { fontSize: 15, fontWeight: '600' as const, color: c.danger, lineHeight: 20 },
  editContent: { paddingHorizontal: Spacing.xl, paddingTop: Spacing.lg },
  editSaveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    backgroundColor: c.primary,
    borderRadius: Radius.xl,
    paddingVertical: Spacing.lg,
    marginTop: Spacing.xs,
  },
  editSaveBtnText: { fontSize: 16, fontWeight: '700' as const, color: c.white, lineHeight: 22 },
  editCancelBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.xl,
    paddingVertical: Spacing.xl,
    marginTop: Spacing.md,
    backgroundColor: c.surfaceAlt,
  },
  editCancelBtnText: { fontSize: 15, fontWeight: '600' as const, color: c.textSecondary, lineHeight: 20 },
  proSection: {
    backgroundColor: c.surface,
    borderRadius: Radius.xl,
    padding: Spacing.lg,
    marginBottom: Spacing.lg,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: Spacing.xs,
    elevation: 1,
  },
  proSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  proTitleRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
  proSectionTitle: { fontSize: 15, fontWeight: '600' as const, color: c.text, lineHeight: 20 },
  proRemoveBtn: { padding: Spacing.xs },
  proCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.primaryLight,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    gap: Spacing.md,
  },
  proAvatarWrap: {
    width: 40,
    height: 40,
    borderRadius: Radius.lg,
    backgroundColor: c.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  proCardInfo: { flex: 1 },
  proCardName: { fontSize: 15, fontWeight: '600' as const, color: c.text, lineHeight: 20 },
  proCardSpecialty: { fontSize: 12, color: c.textSecondary, lineHeight: 16, marginTop: 1 },
  proCardPhoneRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, marginTop: 3 },
  proCardPhone: { fontSize: 12, color: c.textTertiary, lineHeight: 16 },
  proRatingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: c.surface,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: Radius.sm,
  },
  proRatingText: { fontSize: 12, fontWeight: '600' as const, color: c.text, lineHeight: 16 },
  proEmptyState: { alignItems: 'center', paddingVertical: Spacing.sm, gap: Spacing.md },
  proEmptyText: { fontSize: 13, color: c.textTertiary },
  proEmptyActions: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  proSelectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    backgroundColor: c.primaryLight,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    borderRadius: Radius.md,
  },
  proSelectBtnText: { fontSize: 14, fontWeight: '600' as const, color: c.primary, lineHeight: 19 },
  findProBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    backgroundColor: c.primary,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    borderRadius: Radius.md,
  },
  findProBtnText: { fontSize: 14, fontWeight: '600' as const, color: c.white, lineHeight: 19 },
  proPickerWrap: { gap: Spacing.sm },
  proPickerLabel: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: c.textTertiary,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
    marginBottom: Spacing.xs,
  },
  proPickerList: { maxHeight: 200 },
  proPickerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: c.borderLight,
  },
  proPickerAvatar: {
    width: 34,
    height: 34,
    borderRadius: Radius.md,
    backgroundColor: c.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  proPickerInfo: { flex: 1 },
  proPickerName: { fontSize: 14, fontWeight: '600' as const, color: c.text, lineHeight: 19 },
  proPickerSpecialty: { fontSize: 12, color: c.textSecondary, lineHeight: 16 },
  proPickerCancelBtn: { alignItems: 'center', paddingVertical: Spacing.md, marginTop: Spacing.xs },
  proPickerCancelText: { fontSize: 14, fontWeight: '500' as const, color: c.textSecondary },
  proPickerEmpty: { alignItems: 'center', gap: Spacing.md, paddingVertical: Spacing.sm },
  proPickerEmptyText: { fontSize: 13, color: c.textTertiary },
  calendarSection: {
    backgroundColor: c.surface,
    borderRadius: Radius.xl,
    padding: Spacing.lg,
    marginBottom: Spacing.lg,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: Spacing.xs,
    elevation: 1,
  },
  calendarSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    marginBottom: Spacing.xl,
  },
  calendarSectionTitle: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: c.text,
    lineHeight: 20,
  },
  calendarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    marginBottom: Spacing.md,
  },
  calendarRowLast: {
    marginBottom: 0,
  },
  calendarAddBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    backgroundColor: c.surfaceAlt,
    borderRadius: Radius.lg,
    paddingVertical: 13,
    paddingHorizontal: Spacing.xl,
  },
  calendarAddBtnText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: c.text,
    lineHeight: 19,
  },
  calendarAddBtnDisabled: {
    opacity: 0.5,
  },
  calendarSyncedBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    backgroundColor: c.primaryLight,
    borderRadius: Radius.lg,
    paddingVertical: 13,
    paddingHorizontal: Spacing.xl,
  },
  calendarSyncedContent: {
    flex: 1,
  },
  calendarSyncedLabel: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: c.primary,
    lineHeight: 19,
  },
  calendarSyncedSub: {
    fontSize: 11,
    color: c.textTertiary,
    lineHeight: 15,
    marginTop: 1,
  },
  calendarRemoveBtn: {
    padding: Spacing.xs,
  },
  reminderSyncedBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    backgroundColor: c.warningLight,
    borderRadius: Radius.lg,
    paddingVertical: 13,
    paddingHorizontal: Spacing.xl,
  },
  reminderSyncedLabel: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: c.warning,
    lineHeight: 19,
  },
  reminderSyncedSub: {
    fontSize: 11,
    color: c.textTertiary,
    lineHeight: 15,
    marginTop: 1,
  },
  calendarWebNote: {
    fontSize: 12,
    color: c.textTertiary,
    textAlign: 'center' as const,
    marginTop: Spacing.xs,
    lineHeight: 16,
  },
  youtubeList: {
    gap: Spacing.md,
  },
  youtubeCard: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: c.surfaceAlt,
    borderRadius: Radius.lg,
    overflow: 'hidden' as const,
    gap: Spacing.md,
    paddingRight: Spacing.md,
  },
  youtubeThumbnail: {
    width: 88,
    height: 66,
    backgroundColor: '#1A1A1A',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    position: 'relative' as const,
  },
  youtubeThumbnailBg: {
    width: 88,
    height: 66,
    position: 'absolute' as const,
    opacity: 0.15,
  },
  youtubePlayOverlay: {
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    flex: 1,
  },
  youtubePlayBtn: {
    width: 34,
    height: 24,
    borderRadius: Radius.xs,
    backgroundColor: '#FF0000',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  youtubeRedBar: {
    position: 'absolute' as const,
    bottom: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: '#FF0000',
  },
  youtubeCardInfo: {
    flex: 1,
    paddingVertical: Spacing.sm,
    gap: 2,
  },
  youtubeCardTitle: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: c.text,
    lineHeight: 18,
  },
  youtubeCardSub: {
    fontSize: 11,
    color: c.textTertiary,
    lineHeight: 15,
  },
  youtubeSearchRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 3,
    marginTop: 2,
  },
  youtubeSearchHint: {
    fontSize: 10,
    color: c.textTertiary,
    lineHeight: 14,
  },
  youtubeFullSearchBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: Spacing.sm,
    marginTop: Spacing.md,
    paddingVertical: 11,
    paddingHorizontal: Spacing.xl,
    backgroundColor: '#FFF0F0',
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: 'rgba(255,0,0,0.15)',
  },
  youtubeFullSearchText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#CC0000',
    lineHeight: 19,
  },
});

export default createStyles;
