import { StyleSheet } from 'react-native';
import { ColorScheme } from '@/constants/colors';
import { Radius, Spacing, cardShadowXs, cardShadowSm, cardShadowLg } from '@/constants/layout';

const createStyles = (c: ColorScheme) => StyleSheet.create({
  container: { flex: 1, backgroundColor: c.background },
  content: { paddingHorizontal: Spacing.xl, paddingTop: Spacing.lg },
  findCard: { backgroundColor: c.surface, borderRadius: Radius.cardXl, marginBottom: Spacing.xl, ...cardShadowLg(c), overflow: 'hidden' },
  findCardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: Spacing.lg },
  findCardHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  findIconWrap: { width: 42, height: 42, borderRadius: Radius.xl, backgroundColor: c.primary, justifyContent: 'center', alignItems: 'center' },
  findCardTitle: { fontSize: 17, fontWeight: '700', color: c.text, letterSpacing: -0.2 },
  findCardSubtitle: { fontSize: 12, color: c.textSecondary, marginTop: 1 },
  findBody: { paddingHorizontal: Spacing.lg, paddingBottom: 18, borderTopWidth: 1, borderTopColor: c.borderLight, paddingTop: Spacing.xl },
  findInputLabel: { fontSize: 12, fontWeight: '600', color: c.textSecondary, textTransform: 'uppercase' as const, letterSpacing: 0.5, marginBottom: Spacing.sm },
  findInputRow: { gap: Spacing.sm },
  findInputWrap: { flexDirection: 'row', alignItems: 'center', backgroundColor: c.surfaceAlt, borderRadius: Radius.lg, paddingHorizontal: Spacing.md, paddingVertical: Spacing.md, gap: Spacing.sm },
  findInput: { flex: 1, fontSize: 14, color: c.text, padding: 0 },
  selectedApplianceChip: { flex: 1, flexDirection: 'row', alignItems: 'center', backgroundColor: c.primaryLight, borderRadius: Radius.sm, paddingHorizontal: Spacing.md, paddingVertical: 5, gap: Spacing.xs },
  selectedApplianceText: { flex: 1, fontSize: 13, fontWeight: '600', color: c.primary },
  orApplianceBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.xs, marginTop: Spacing.sm, paddingVertical: Spacing.xs },
  orApplianceText: { fontSize: 13, fontWeight: '600', color: c.primary },
  findRadiusRow: { gap: Spacing.sm },
  findRadiusChip: { paddingHorizontal: Spacing.lg, paddingVertical: Spacing.sm, borderRadius: Radius.md, backgroundColor: c.surfaceAlt, borderWidth: 1.5, borderColor: 'transparent' },
  findRadiusChipActive: { backgroundColor: c.primaryLight, borderColor: c.primary },
  findRadiusChipText: { fontSize: 13, fontWeight: '600', color: c.textSecondary },
  findRadiusChipTextActive: { color: c.primary },
  searchButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.md, marginTop: 18, backgroundColor: c.primary, borderRadius: Radius.xl, paddingVertical: Spacing.xl },
  searchButtonDisabled: { backgroundColor: c.surfaceAlt },
  searchButtonText: { fontSize: 15, fontWeight: '700', color: c.white },
  findHint: { fontSize: 12, color: c.textTertiary, textAlign: 'center' as const, marginTop: Spacing.md },
  loadingWrap: { alignItems: 'center', paddingVertical: Spacing.xxxxl, gap: Spacing.md },
  loadingText: { fontSize: 14, color: c.textSecondary },
  noResultsWrap: { alignItems: 'center', paddingVertical: Spacing.xxxl, gap: Spacing.sm },
  noResultsTitle: { fontSize: 16, fontWeight: '700', color: c.text },
  noResultsText: { fontSize: 13, color: c.textTertiary, textAlign: 'center' as const },
  resultsSection: { marginTop: 18 },
  paginationRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: Spacing.sm, marginTop: Spacing.xl, marginBottom: Spacing.xs },
  paginationBtn: { width: 34, height: 34, borderRadius: Radius.md, backgroundColor: c.surfaceAlt, justifyContent: 'center', alignItems: 'center' },
  paginationBtnActive: { backgroundColor: c.primary },
  paginationText: { fontSize: 13, fontWeight: '600', color: c.textSecondary },
  paginationTextActive: { color: c.white },
  resultsHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: Spacing.md },
  resultsTitle: { fontSize: 14, fontWeight: '700', color: c.text },
  clearResultsText: { fontSize: 13, fontWeight: '600', color: c.primary },
  resultCard: { backgroundColor: c.surfaceAlt, borderRadius: Radius.xl, padding: Spacing.xl, marginBottom: Spacing.md },
  resultTop: { flexDirection: 'row', alignItems: 'center', marginBottom: Spacing.md },
  resultAvatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: c.primary, justifyContent: 'center', alignItems: 'center', marginRight: Spacing.md },
  resultAvatarText: { fontSize: 17, fontWeight: '700', color: c.white },
  resultInfo: { flex: 1 },
  resultName: { fontSize: 15, fontWeight: '700', color: c.text, lineHeight: 20 },
  resultRatingRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 3 },
  resultRatingText: { fontSize: 13, fontWeight: '700', color: c.warning },
  resultReviewCount: { fontSize: 12, color: c.textTertiary },
  saveBtn: { width: 36, height: 36, borderRadius: Radius.cardLg, backgroundColor: c.primary, justifyContent: 'center', alignItems: 'center', marginLeft: Spacing.sm },
  saveBtnSaved: { backgroundColor: c.primaryLight },
  resultDetails: { gap: Spacing.xs, paddingLeft: 52 },
  resultDetailRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  resultDetailText: { fontSize: 13, color: c.textSecondary, flex: 1, lineHeight: 17 },
  resultDetailLink: { color: c.primary },
  savedBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: Spacing.md, paddingLeft: 52 },
  savedBadgeText: { fontSize: 12, fontWeight: '600', color: c.primary },
  savedHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: Spacing.md },
  savedHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  savedHeaderTitle: { fontSize: 18, fontWeight: '700', color: c.text, letterSpacing: -0.3 },
  savedCountBadge: { backgroundColor: c.primaryLight, paddingHorizontal: Spacing.md, paddingVertical: Spacing.xs, borderRadius: Radius.md },
  savedCountText: { fontSize: 13, fontWeight: '700', color: c.primary },
  searchRow: { flexDirection: 'row', gap: Spacing.md, marginBottom: Spacing.md },
  searchInputWrap: { flex: 1, flexDirection: 'row', alignItems: 'center', backgroundColor: c.surface, borderRadius: Radius.xl, paddingHorizontal: Spacing.xl, height: 46, gap: Spacing.md, ...cardShadowXs(c) },
  searchInput: { flex: 1, fontSize: 14, color: c.text, padding: 0 },
  filterToggleBtn: { width: 46, height: 46, borderRadius: Radius.xl, backgroundColor: c.primaryLight, justifyContent: 'center', alignItems: 'center' },
  filterToggleBtnActive: { backgroundColor: c.primary },
  filterBadge: { position: 'absolute', top: Spacing.xs, right: Spacing.xs, width: 16, height: 16, borderRadius: Spacing.sm, backgroundColor: c.warning, justifyContent: 'center', alignItems: 'center' },
  filterBadgeText: { fontSize: 9, fontWeight: '700', color: c.white },
  filtersWrap: { overflow: 'hidden', marginBottom: Spacing.xs },
  filterSection: { marginBottom: Spacing.md },
  filterLabelRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: Spacing.sm },
  filterLabelIconRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
  filterLabel: { fontSize: 12, fontWeight: '600', color: c.textSecondary, textTransform: 'uppercase' as const, letterSpacing: 0.5 },
  filterClearText: { fontSize: 12, fontWeight: '600', color: c.primary },
  filterChipsRow: { gap: Spacing.xs, paddingRight: Spacing.md },
  filterChip: { paddingHorizontal: Spacing.md, paddingVertical: 7, borderRadius: Radius.md, backgroundColor: c.surface, borderWidth: 1, borderColor: c.borderLight },
  filterChipActive: { backgroundColor: c.primaryLight, borderColor: c.primary },
  filterChipText: { fontSize: 12, fontWeight: '600', color: c.textSecondary },
  filterChipTextActive: { color: c.primaryDark },
  radiusRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.xs },
  radiusChip: { paddingHorizontal: Spacing.xl, paddingVertical: 7, borderRadius: Radius.md, backgroundColor: c.surface, borderWidth: 1, borderColor: c.borderLight },
  radiusChipActive: { backgroundColor: c.primaryLight, borderColor: c.primary },
  radiusChipText: { fontSize: 12, fontWeight: '600', color: c.textSecondary },
  radiusChipTextActive: { color: c.primary },
  activeFilterSummary: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: Spacing.sm, paddingHorizontal: Spacing.xs, marginBottom: Spacing.sm },
  activeFilterText: { fontSize: 13, color: c.textSecondary, fontWeight: '500' },
  clearAllText: { fontSize: 13, fontWeight: '600', color: c.primary },
  emptyState: { backgroundColor: c.surface, borderRadius: Radius.cardXl, padding: 36, alignItems: 'center' },
  emptyIconWrap: { width: 60, height: 60, borderRadius: 30, backgroundColor: c.surfaceAlt, justifyContent: 'center', alignItems: 'center', marginBottom: Spacing.xl },
  emptyTitle: { fontSize: 17, fontWeight: '700', color: c.text, marginBottom: Spacing.xs },
  emptySubtext: { fontSize: 14, color: c.textTertiary, textAlign: 'center' as const, lineHeight: 20, marginBottom: Spacing.md },
  emptyResetBtn: { paddingHorizontal: Spacing.xl, paddingVertical: Spacing.md, borderRadius: Radius.md, backgroundColor: c.primaryLight },
  emptyResetText: { fontSize: 14, fontWeight: '600', color: c.primary },
  proCard: { backgroundColor: c.surface, borderRadius: Radius.card, padding: Spacing.lg, marginBottom: Spacing.md, ...cardShadowSm(c) },
  proTop: { flexDirection: 'row', alignItems: 'center', marginBottom: Spacing.md },
  proAvatar: { width: 46, height: 46, borderRadius: 23, backgroundColor: c.primary, justifyContent: 'center', alignItems: 'center', marginEnd: Spacing.md },
  proAvatarText: { fontSize: 18, fontWeight: '700', color: c.white },
  proMainInfo: { flex: 1 },
  proName: { fontSize: 16, fontWeight: '700', color: c.text, marginBottom: 1, lineHeight: 21 },
  proSpecialty: { fontSize: 13, color: c.textSecondary, lineHeight: 17 },
  proRatingRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, marginTop: 3 },
  proRatingText: { fontSize: 12, fontWeight: '700', color: c.warning },
  proRatingCount: { fontSize: 11, color: c.textTertiary },
  deleteBtn: { width: 36, height: 36, borderRadius: Radius.lg, backgroundColor: c.dangerLight, justifyContent: 'center', alignItems: 'center' },
  proDetails: { gap: Spacing.xs, paddingLeft: 58, marginBottom: Spacing.md },
  proDetailRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  proDetailText: { fontSize: 13, color: c.textSecondary, flex: 1, lineHeight: 17 },
  proTagsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.xs, paddingLeft: 58, marginBottom: Spacing.md, alignItems: 'center' },
  proTag: { backgroundColor: c.primaryLight, paddingHorizontal: Spacing.sm, paddingVertical: 3, borderRadius: Radius.xs },
  proTagText: { fontSize: 11, fontWeight: '600', color: c.primaryDark },
  proTagMore: { fontSize: 11, fontWeight: '600', color: c.textTertiary },
  proRadiusBadge: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: c.primaryLight, paddingHorizontal: 7, paddingVertical: 3, borderRadius: Radius.xs },
  proRadiusText: { fontSize: 11, fontWeight: '600', color: c.primary },
  proFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: c.borderLight, paddingTop: Spacing.md },
  proFooterLeft: { flexDirection: 'row', gap: Spacing.sm, alignItems: 'center' },
  proExpenseBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 9, paddingVertical: Spacing.xs, backgroundColor: c.primaryLight, borderRadius: Radius.sm },
  proExpenseText: { fontSize: 11, fontWeight: '600', color: c.primary, lineHeight: 15 },
  proLinkedBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 9, paddingVertical: Spacing.xs, backgroundColor: c.primaryLight, borderRadius: Radius.sm },
  proLinkedText: { fontSize: 11, fontWeight: '600', color: c.primary, lineHeight: 15 },
  modalOverlay: { flex: 1, backgroundColor: c.overlay, justifyContent: 'flex-end' },
  modalContent: { backgroundColor: c.surface, borderTopLeftRadius: Radius.sheet, borderTopRightRadius: Radius.sheet, maxHeight: '70%', paddingTop: Spacing.xl, paddingHorizontal: Spacing.xl },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: Spacing.xs },
  modalTitle: { fontSize: 20, fontWeight: '700', color: c.text },
  modalSubtitle: { fontSize: 13, color: c.textSecondary, marginBottom: Spacing.lg, lineHeight: 18 },
  appliancePickerItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: Spacing.xl, paddingHorizontal: Spacing.xs, borderBottomWidth: 1, borderBottomColor: c.borderLight },
  appliancePickerLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: Spacing.md },
  appliancePickerIcon: { width: 40, height: 40, borderRadius: Radius.lg, backgroundColor: c.primaryLight, justifyContent: 'center', alignItems: 'center' },
  appliancePickerInfo: { flex: 1 },
  appliancePickerName: { fontSize: 15, fontWeight: '600', color: c.text, marginBottom: 2 },
  appliancePickerMeta: { fontSize: 12, color: c.textSecondary },
  appliancePickerService: { fontSize: 11, color: c.primary, fontWeight: '500', marginTop: 2 },
  emptyModalState: { paddingVertical: 40, alignItems: 'center' },
  emptyModalText: { fontSize: 14, color: c.textTertiary },
  addProBtn: { width: 32, height: 32, borderRadius: Radius.lg, backgroundColor: c.primary, justifyContent: 'center', alignItems: 'center' },
  addProModalOverlay: { flex: 1, backgroundColor: c.overlay, justifyContent: 'flex-end' },
  addProModalContent: { backgroundColor: c.surface, borderTopLeftRadius: Radius.sheet, borderTopRightRadius: Radius.sheet, maxHeight: '92%', paddingBottom: Spacing.xl },
  addProModalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: Spacing.xl, paddingTop: Spacing.xl, paddingBottom: Spacing.md },
  addProModalTitle: { fontSize: 20, fontWeight: '700' as const, color: c.text, letterSpacing: -0.3 },
  addProModalSubtitle: { fontSize: 13, color: c.textSecondary, paddingHorizontal: Spacing.xl, marginBottom: Spacing.lg, lineHeight: 18 },
  addProScrollContent: { paddingHorizontal: Spacing.xl, paddingBottom: 40 },
  addProSectionLabel: { fontSize: 11, fontWeight: '700' as const, color: c.textTertiary, textTransform: 'uppercase' as const, letterSpacing: 0.8, marginTop: Spacing.xl, marginBottom: Spacing.md },
  addProFieldRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: c.surfaceAlt, borderRadius: Radius.lg, paddingHorizontal: Spacing.md, paddingVertical: Spacing.md, gap: Spacing.sm, marginBottom: Spacing.sm },
  addProFieldInput: { flex: 1, fontSize: 14, color: c.text, padding: 0 },
  addProNotesInput: { flex: 1, fontSize: 14, color: c.text, padding: 0, minHeight: 50, textAlignVertical: 'top' as const },
  addProInsuranceRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: c.surfaceAlt, borderRadius: Radius.lg, paddingHorizontal: Spacing.md, paddingVertical: Spacing.lg, gap: Spacing.sm, marginBottom: Spacing.sm },
  addProInsuranceText: { flex: 1, fontSize: 14 },
  addProCatGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  addProCatChip: { paddingHorizontal: Spacing.md, paddingVertical: 8, borderRadius: Radius.md, backgroundColor: c.surfaceAlt, borderWidth: 1.5, borderColor: 'transparent' },
  addProCatChipActive: { backgroundColor: c.primaryLight, borderColor: c.primary },
  addProCatChipText: { fontSize: 12, fontWeight: '600' as const, color: c.textSecondary },
  addProCatChipTextActive: { color: c.primary },
  addProRadiusRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, marginTop: Spacing.sm },
  addProRadiusChip: { paddingHorizontal: Spacing.lg, paddingVertical: 8, borderRadius: Radius.md, backgroundColor: c.surfaceAlt, borderWidth: 1.5, borderColor: 'transparent' },
  addProRadiusChipActive: { backgroundColor: c.primaryLight, borderColor: c.primary },
  addProRadiusChipText: { fontSize: 12, fontWeight: '600' as const, color: c.textSecondary },
  addProRadiusChipTextActive: { color: c.primary },
  addProApplianceRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: Spacing.md, paddingHorizontal: Spacing.xs, borderBottomWidth: 1, borderBottomColor: c.borderLight, gap: Spacing.md },
  addProApplianceDot: { width: 10, height: 10, borderRadius: 5 },
  addProApplianceInfo: { flex: 1 },
  addProApplianceName: { fontSize: 14, fontWeight: '600' as const, color: c.text },
  addProApplianceMeta: { fontSize: 12, color: c.textSecondary, marginTop: 1 },
  addProCheckbox: { width: 24, height: 24, borderRadius: Radius.sm, borderWidth: 2, borderColor: c.border, justifyContent: 'center', alignItems: 'center' },
  addProCheckboxActive: { backgroundColor: c.primary, borderColor: c.primary },
  addProEmptyAppliances: { paddingVertical: Spacing.xl, alignItems: 'center' },
  addProEmptyAppliancesText: { fontSize: 13, color: c.textTertiary },
  addProSaveBtn: { backgroundColor: c.primary, borderRadius: Radius.xl, paddingVertical: Spacing.lg, alignItems: 'center', justifyContent: 'center', marginTop: Spacing.xxl },
  addProSaveBtnDisabled: { backgroundColor: c.surfaceAlt },
  addProSaveBtnText: { fontSize: 16, fontWeight: '700' as const, color: c.white },
});

export default createStyles;
