import { StyleSheet } from 'react-native';
import { ColorScheme } from '@/constants/colors';

const createStyles = (c: ColorScheme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: c.background,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  findCard: {
    backgroundColor: c.surface,
    borderRadius: 20,
    marginBottom: 20,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 16,
    elevation: 3,
    overflow: 'hidden',
  },
  findCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
  },
  findCardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  findIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: c.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  findCardTitle: {
    fontSize: 17,
    fontWeight: '700' as const,
    color: c.text,
    letterSpacing: -0.2,
  },
  findCardSubtitle: {
    fontSize: 12,
    color: c.textSecondary,
    marginTop: 1,
  },
  findBody: {
    paddingHorizontal: 16,
    paddingBottom: 18,
    borderTopWidth: 1,
    borderTopColor: c.borderLight,
    paddingTop: 14,
  },
  findInputLabel: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: c.textSecondary,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  findInputRow: {
    gap: 8,
  },
  findInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.surfaceAlt,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  findInput: {
    flex: 1,
    fontSize: 14,
    color: c.text,
    padding: 0,
  },
  selectedApplianceChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.primaryLight,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    gap: 6,
  },
  selectedApplianceText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600' as const,
    color: c.primary,
  },
  orApplianceBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    marginTop: 8,
    paddingVertical: 6,
  },
  orApplianceText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: c.primary,
  },
  findRadiusRow: {
    gap: 8,
  },
  findRadiusChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: c.surfaceAlt,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  findRadiusChipActive: {
    backgroundColor: c.primaryLight,
    borderColor: c.primary,
  },
  findRadiusChipText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: c.textSecondary,
  },
  findRadiusChipTextActive: {
    color: c.primary,
  },
  searchButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginTop: 18,
    backgroundColor: c.primary,
    borderRadius: 14,
    paddingVertical: 14,
  },
  searchButtonDisabled: {
    backgroundColor: c.surfaceAlt,
  },
  searchButtonText: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: c.white,
  },
  findHint: {
    fontSize: 12,
    color: c.textTertiary,
    textAlign: 'center' as const,
    marginTop: 10,
  },
  loadingWrap: {
    alignItems: 'center',
    paddingVertical: 32,
    gap: 12,
  },
  loadingText: {
    fontSize: 14,
    color: c.textSecondary,
  },
  noResultsWrap: {
    alignItems: 'center',
    paddingVertical: 28,
    gap: 8,
  },
  noResultsTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: c.text,
  },
  noResultsText: {
    fontSize: 13,
    color: c.textTertiary,
    textAlign: 'center' as const,
  },
  resultsSection: {
    marginTop: 18,
  },
  paginationRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: 14,
    marginBottom: 4,
  },
  paginationBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: c.surfaceAlt,
    justifyContent: 'center',
    alignItems: 'center',
  },
  paginationBtnActive: {
    backgroundColor: c.primary,
  },
  paginationText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: c.textSecondary,
  },
  paginationTextActive: {
    color: c.white,
  },
  resultsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  resultsTitle: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: c.text,
  },
  clearResultsText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: c.primary,
  },
  resultCard: {
    backgroundColor: c.surfaceAlt,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
  },
  resultTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  resultAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: c.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  resultAvatarText: {
    fontSize: 17,
    fontWeight: '700' as const,
    color: c.white,
  },
  resultInfo: {
    flex: 1,
  },
  resultName: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: c.text,
    lineHeight: 20,
  },
  resultRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 3,
  },
  starsRow: {
    flexDirection: 'row',
    gap: 1,
  },
  resultRatingText: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: c.warning,
  },
  resultReviewCount: {
    fontSize: 12,
    color: c.textTertiary,
  },
  saveBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: c.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  saveBtnSaved: {
    backgroundColor: c.primaryLight,
  },
  resultDetails: {
    gap: 6,
    paddingLeft: 52,
  },
  resultDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  resultDetailText: {
    fontSize: 13,
    color: c.textSecondary,
    flex: 1,
    lineHeight: 17,
  },
  resultDetailLink: {
    color: c.primary,
  },
  savedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 10,
    paddingLeft: 52,
  },
  savedBadgeText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: c.primary,
  },
  savedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  savedHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  savedHeaderTitle: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: c.text,
    letterSpacing: -0.3,
  },
  savedCountBadge: {
    backgroundColor: c.primaryLight,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  savedCountText: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: c.primary,
  },
  searchRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  searchInputWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.surface,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 10,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 1,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: c.text,
    padding: 0,
  },
  filterToggleBtn: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: c.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterToggleBtnActive: {
    backgroundColor: c.primary,
  },
  filterBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: c.warning,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterBadgeText: {
    fontSize: 9,
    fontWeight: '700' as const,
    color: c.white,
  },
  filtersWrap: {
    overflow: 'hidden',
    marginBottom: 4,
  },
  filterSection: {
    marginBottom: 12,
  },
  filterLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  filterLabelIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  filterLabel: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: c.textSecondary,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
  filterClearText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: c.primary,
  },
  filterChipsRow: {
    gap: 6,
    paddingRight: 10,
  },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.borderLight,
  },
  filterChipActive: {
    backgroundColor: c.primaryLight,
    borderColor: c.primary,
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: c.textSecondary,
  },
  filterChipTextActive: {
    color: c.primaryDark,
  },
  radiusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  radiusChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.borderLight,
  },
  radiusChipActive: {
    backgroundColor: c.primaryLight,
    borderColor: c.primary,
  },
  radiusChipText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: c.textSecondary,
  },
  radiusChipTextActive: {
    color: c.primary,
  },
  activeFilterSummary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 4,
    marginBottom: 8,
  },
  activeFilterText: {
    fontSize: 13,
    color: c.textSecondary,
    fontWeight: '500' as const,
  },
  clearAllText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: c.primary,
  },
  emptyState: {
    backgroundColor: c.surface,
    borderRadius: 20,
    padding: 36,
    alignItems: 'center',
  },
  emptyIconWrap: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: c.surfaceAlt,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: '700' as const,
    color: c.text,
    marginBottom: 6,
  },
  emptySubtext: {
    fontSize: 14,
    color: c.textTertiary,
    textAlign: 'center' as const,
    lineHeight: 20,
    marginBottom: 12,
  },
  emptyResetBtn: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: c.primaryLight,
  },
  emptyResetText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: c.primary,
  },
  proCard: {
    backgroundColor: c.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: c.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 1,
  },
  proTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  proAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: c.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  proAvatarText: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: c.white,
  },
  proMainInfo: {
    flex: 1,
  },
  proName: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: c.text,
    marginBottom: 1,
    lineHeight: 21,
  },
  proSpecialty: {
    fontSize: 13,
    color: c.textSecondary,
    lineHeight: 17,
  },
  proRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 3,
  },
  proRatingText: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: c.warning,
  },
  proRatingCount: {
    fontSize: 11,
    color: c.textTertiary,
  },
  deleteBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: c.dangerLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  proDetails: {
    gap: 6,
    paddingLeft: 58,
    marginBottom: 10,
  },
  proDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  proDetailText: {
    fontSize: 13,
    color: c.textSecondary,
    flex: 1,
    lineHeight: 17,
  },
  proTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    paddingLeft: 58,
    marginBottom: 10,
    alignItems: 'center',
  },
  proTag: {
    backgroundColor: c.primaryLight,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  proTagText: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: c.primaryDark,
  },
  proTagMore: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: c.textTertiary,
  },
  proRadiusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: c.primaryLight,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 6,
  },
  proRadiusText: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: c.primary,
  },
  proFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: c.borderLight,
    paddingTop: 12,
  },
  proFooterLeft: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  proExpenseBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 4,
    backgroundColor: c.primaryLight,
    borderRadius: 8,
  },
  proExpenseText: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: c.primary,
    lineHeight: 15,
  },
  proLinkedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 4,
    backgroundColor: c.primaryLight,
    borderRadius: 8,
  },
  proLinkedText: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: c.primary,
    lineHeight: 15,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: c.overlay,
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: c.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '70%',
    paddingTop: 20,
    paddingHorizontal: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700' as const,
    color: c.text,
  },
  modalSubtitle: {
    fontSize: 13,
    color: c.textSecondary,
    marginBottom: 16,
    lineHeight: 18,
  },
  appliancePickerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: c.borderLight,
  },
  appliancePickerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 12,
  },
  appliancePickerIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: c.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  appliancePickerInfo: {
    flex: 1,
  },
  appliancePickerName: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: c.text,
    marginBottom: 2,
  },
  appliancePickerMeta: {
    fontSize: 12,
    color: c.textSecondary,
  },
  appliancePickerService: {
    fontSize: 11,
    color: c.primary,
    fontWeight: '500' as const,
    marginTop: 2,
  },
  emptyModalState: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  emptyModalText: {
    fontSize: 14,
    color: c.textTertiary,
  },
});

export default createStyles;
